### ISSUE TITLE
Documentation link not found

### ISSUE THREAD

**Issue by perkooo** [mattermost/mattermost-plugin-calls#100]
The documentation link in the plugin: https://docs.mattermost.com/channels/make-calls.html doesn't seem to work.

Would you have an updated link please? :)

**Comment by streamer45** [comment]
@perkooo 

That's the right link, just not ready yet. It should be up soon though, will keep you posted.

**Comment by perkooo** [comment]
Noted, thanks.

**Comment by streamer45** [comment]
Documentation link should be available now.
