### ISSUE TITLE
Failed to get public IP address

### ISSUE THREAD

**Issue by gamelaster** [mattermost/mattermost-plugin-calls#110]
We are using Mattermost Professional 7.0.0 which ships with Calls 0.6.0. When I try to enable the plugin, following error is in console:
```json
{"timestamp":"2022-06-15 09:25:23.784 +02:00","level":"info","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:61","plugin_id":"com.mattermost.calls","wrapped_extras":"path/mattermost/plugins/com.mattermost.calls/server/dist/plugin-linux-amd64pid319"}
{"timestamp":"2022-06-15 09:25:23.784 +02:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:139","plugin_id":"com.mattermost.calls","error":"failed to get public IP address: failed to get public address: read udp4 0.0.0.0:8443: i/o timeout"}
```

We are running mattermost in official Docker-compose container, but within internal network (the Mattermost server is available only within LAN).

**Comment by FelixSFD** [comment]
I'm having the same issue on the Team Edition in our Docker Swarm: https://forum.mattermost.com/t/error-activating-calls-plugin-docker-swarm/13559

**Comment by streamer45** [comment]
@gamelaster If you are using it internally, I'd suggest setting the "ICE Host Override" config option to the IP address the Mattermost instance is reachable on.

**Comment by FelixSFD** [comment]
@streamer45 Thank you! :-) This helped resolving my issue.

```json
"com.mattermost.calls": {
    "allowenablecalls": true,
    "defaultenabled": false,
    "icehostoverride": "<hostname>",
    "iceservers": "stun:stun.global.calls.mattermost.com:3478",
    "maxcallparticipants": 0,
    "rtcdserviceurl": null,
    "udpserverport": 8965
},
```

`<hostname>` is a placeholder for the DNS-Name our Docker Swarm is using. I've changed the port to 8965 and configured that port as UDP (if you don't specify the protocol, Docker will use TCP by default) in the compose-file.

**Comment by gamelaster** [comment]
> I've changed the port to 8965 and configured that port as UDP (if you don't specify the protocol, Docker will use TCP by default) in the compose-file.

@FelixSFD this might be issue I currently have with it, gonna try it, thanks!
