### ISSUE TITLE
Plugin support for Kubernetes with Oprator

### ISSUE THREAD

**Issue by sbaerlocher** [mattermost/mattermost-plugin-calls#121]
Can you write a tutorial on how to set up the plugin on a Kubernetes cluster related to the Mattermost operator?

A simple NodePort pointing to the container does not work.

**Comment by streamer45** [comment]
@angeloskyratzakos Would you be able to help here?

**Comment by angeloskyratzakos** [comment]
Let's create a ticket to discuss it, as I am not sure how we can implement it without the RTCD component

**Comment by angeloskyratzakos** [comment]
@sbaerlocher as quick overview, in Cloud we deploy the [RTCD](https://github.com/mattermost/rtcd) via the respective [helm chart](https://artifacthub.io/packages/helm/mattermost/mattermost-rtcd) and then calls plugin uses it(RTCD) to host calls

**Comment by streamer45** [comment]
Closing this as the current supported way would be to use the helm chart.
