### ISSUE TITLE
Calls Permission 

### ISSUE THREAD

**Issue by jasonmacer** [mattermost/mattermost-plugin-calls#124]
So it looks like a user must be an "administrator" to utilize the calls feature.

Summary
We recently upgraded our on premises version to 7.0, and now have access to calls. They do work; however, both users have to be admins for the calls to complete from each end. Is there a way around this?

Steps to reproduce
Start a call from an admin to non admin and the non admin cannot join
Non admin’s cannot start a call

Expected behavior
Admin and Non admin users should be able to start and join calls

Observed behavior
Non admins cannot join or create calls

**Comment by jasonmacer** [comment]
No, I have a standard user, I am in a direct message with him, and I start a call. He is not able to join the call. 

Likewise he cannot start a call. 

Now, when I give him admin permissions, he can join the call or start calls, but when i remove those permissions again he is no longer able to join or start calls.  And, like i said this is in a direct message.

**Comment by streamer45** [comment]
> No, I have a standard user, I am in a direct message with him, and I start a call. He is not able to join the call.

Okay, can the normal user see the join/start call buttons and clicking them does nothing or something else?

**Comment by jasonmacer** [comment]
@streamer45, correct. It is a button and cannot join or create.

Something strange, I have (1) user who can (i'm checking his permissions now), but the others cannot. 

I will post permissions shortly, but everyone is usually created with a "basic" profile that is identical.

**Comment by streamer45** [comment]
Alright. I am thinking there could be an unrelated issues with certain users. I think it would be helpful to share client logs from the users that are failing to join/start.

Please refer to [this document](https://docs.google.com/document/d/10PF7PGFH3Xii1beGFk3pi5jrsZjGKwll3F388ZI75wU/edit?usp=sharing) for details on how to retrieve client-side logs.

**Comment by jasonmacer** [comment]
@streamer45, so something interesting just happened ... it started working.

I did not change any of their permissions, but it did just start working. It was almost like there was a delayed join call, delayed by about 15-20 seconds (i'm guessing).  I do have the document and I am going to have them use this today and a couple of times to make sure it works and pull logging to see if the issue pops up again.

🤦‍♂️ gotta love technology!
