### ISSUE TITLE
Update Plugin To Work On Mattermost Server Hosted on NGINX Sub Path

### ISSUE THREAD

**Issue by ndgayan** [mattermost/mattermost-plugin-calls#130]
Our Mattermost server is hosted on https://example.com/mattermost/ using the NGINX subfolder. When I start a call, it tries to establish a web socket connection to 'wss://example.com/api/v4/websocket' and it failed. You can see the sub-folder path is missing in the URL. Could you update the plugin to read the sub-folder from the server configuration? I saw this issue in a lot of other plugins. 

The correct request should be 'wss://example.com/mattermost/api/v4/websocket'

**Comment by streamer45** [comment]
Hi @ndgayan , this should be fixed as of https://github.com/mattermost/mattermost-plugin-calls/issues/112 . It will be included in the release.

**Comment by ndgayan** [comment]
Thanks, @streamer45
