### ISSUE TITLE
Screen sharing during call does not work in Desktop App

### ISSUE THREAD

**Issue by torse** [mattermost/mattermost-plugin-calls#131]
As per request, I move this issue here: https://github.com/mattermost/desktop/issues/2172#issuecomment-1165357122

Please find also attached the JS Console Logs:
[mattermost-1656062035567.log](https://github.com/mattermost/mattermost-plugin-calls/files/8974901/mattermost-1656062035567.log)

The `/call stats` command in the channel returns: `Error: Empty stats object`

**Comment by streamer45** [comment]
@torse Did you enable experimental features by any chance? I see a `DOMException: Could not start audio source` error there which doesn't make much sense unless you are trying to capture audio along with the screen sharing.

**Comment by torse** [comment]
Thankls for the hint, @streamer45. 

Hm, indeed I might have enabled them after unsuccessful testing the calls plugin. However, I just looked and couldn't find anything special or related to the calls plugin in the System Console > Experimental > Features configuration. Also in the calls plugin settings I couldn't find a toggle to enable experimental features. 

Can you point me to the specific setting you have in mind?

**Comment by streamer45** [comment]
You would need to enter the `/call experimental on` or `/call experimental off` commands respectively.

**Comment by jonwsoto** [comment]
> Indeed, disabling the features with the `/call experimental off` command fixes the issue and now the screen sharing also works in the desktop app!
> 
> I now remember that I enabled it after having troubles getting calls to work. But the reason was in hindsight that the RTC server port (8443) wasn't exposed as I use the docker deployment and had to manually set it in the docker-compose config. I forgot about it as the screen sharing worked for me afterwards with Firefox and Chrome even with `eperimental on`.
> 
> So I guess the issue can be closed. Thanks a lot for your help!

Can you share how you exposed the port in the config?

**Comment by torse** [comment]
> Can you share how you exposed the port in the config?

I've added the line `-8443:8443` in the `docker-compose.without-nginx.yml` to expose the RTC server port:

```yaml
...
 services:
   mattermost:
     ports:
       - ${APP_PORT}:8065
       - 8443:8443
...
```
