### ISSUE TITLE
Who's talking is not showing without a trick

### ISSUE THREAD

**Issue by H-B-Schmidt** [mattermost/mattermost-plugin-calls#138]
Mattermost 7.0.1 - Calls 0.7

To see who's talking the participants have to mute/unmute their mics first. Otherwise Calls popup window is displaying 'no one is talking'.

**Comment by streamer45** [comment]
The voice detection system has been changed in the last release which should hopefully improve this. I'll close this for now but let us know if you encounter more related issues.
