### ISSUE TITLE
STUN/TURN not working

### ISSUE THREAD

**Issue by H-B-Schmidt** [mattermost/mattermost-plugin-calls#140]
I wanted to test STUN/TURN and did set media.peerconnection.ice.relay_only to TRUE in my Firefox about:config. 

I then started a call and it immediately ended. Firefox tab about:webrtc is showing this:
![grafik](https://user-images.githubusercontent.com/5337950/177753694-76639845-bfc0-4532-ad13-a6bfb8b227b1.png)

So there is no candidate found. 

Btw is Calls supporting something like turns:turn.server.de:443 instead of stun for ICE Server?
If I enter this for my TURN Server and check with Firefox, no ICE Server is displayed at all with about:webrtc

**Comment by streamer45** [comment]
TURN servers are supported as of the latest version (0.7.0) but you need to configure a valid TURN server.
You can check https://github.com/mattermost/mattermost-plugin-calls/issues/49#issuecomment-1153843016 for more details.

**Comment by H-B-Schmidt** [comment]
We have a valid TURN server configured which we already use for BigBlueButton. 
I configured Calls 0.7 with that server and the the corresponding secret. 
Nevertheless the connection fails for a certain user.

> info  [2022-07-07 13:50:42.602 +02:00] pc ERROR: 2022/07/07 13:50:42 Incoming unhandled RTP ssrc(1715693658), OnTrack will not be fired. mid RTP Extensions required for Simulcast
 caller="io/io.go:428" plugin_id=com.mattermost.calls source=plugin_stdout
error [2022-07-07 13:50:58.685 +02:00] failed to read RTP packet                     caller="app/plugin_api.go:940" plugin_id=com.mattermost.calls origin="main.(*logger).Error log.go:92" error=EOF
error [2022-07-07 13:50:59.299 +02:00] failed to read RTP packet                     caller="app/plugin_api.go:940" plugin_id=com.mattermost.calls origin="main.(*logger).Error log.go:92" error=EOF
info  [2022-07-07 13:51:18.888 +02:00] pc ERROR: 2022/07/07 13:51:18 Incoming unhandled RTP ssrc(1111726716), OnTrack will not be fired. mid RTP Extensions required for Simulcast
 caller="io/io.go:428" plugin_id=com.mattermost.calls source=plugin_stdout
error [2022-07-07 13:51:38.967 +02:00] failed to read RTP packet                     caller="app/plugin_api.go:940" plugin_id=com.mattermost.calls origin="main.(*logger).Error log.go:92" error=EOF
error [2022-07-07 13:51:39.983 +02:00] failed to read RTP packet                     caller="app/plugin_api.go:940" plugin_id=com.mattermost.calls origin="main.(*logger).Error log.go:92" error=EOF

What can I do to debug the problem?
Server Side TURN is set to true but I'm no exactly sure what that does.

Thanks for your support and the great plugin. Our institute would love to use it.

**Comment by H-B-Schmidt** [comment]
Thanks. Is it possible to document the plugin and its settings a bit more for those who are not native ICE/STUN/TURN admins?
What is the best solution to get maximum connectivity. I guess it is a working TURN Server on Port 443?
What is the disadvantage of enabling 'Server Side TURN' as it is offered as an option?
Do I have to configure an additional STUN server in 'ICE Servers Configurations' when I already have configured a TURN server?

**Comment by streamer45** [comment]
For maximum client connectivity you'd likely need a TURN server running on port 443 (both TCP/UDP). [`coturn`](https://github.com/coturn/coturn) is probably the widest used implementation as it offers good performance.

> What is the disadvantage of enabling 'Server Side TURN' as it is offered as an option?

Server side TURN is generally not necessary as the assumption is that the server is able to reach the TURN server. I left it as an option to be thorough but it's unlikely to be needed in most setups. When enabled, the server will try to generate TURN relay candidates as well as opposed to only having clients do it (default behaviour).

> Do I have to configure an additional STUN server in 'ICE Servers Configurations' when I already have configured a TURN server?

I'd suggest having a STUN server as well in case clients can find a more optimal way to connect that doesn't involve relaying the data through TURN. In fact if you use `coturn` it can also embed STUN so you get both at the same time.

**Comment by H-B-Schmidt** [comment]
Thanks. The 'ICE Servers Configuration' seems extremely picky about the syntax and line breaks. Shouldn't this work?

> [{
"urls": ["stun:turnsrv01.xxx.yyy.de:3478",
"turn:turnsrv01.xxx.yyy.de:443?transport=udp",
"turn:turnsrv01.xxx.yyy.de:443?transport=tcp"]
}]

It only works if I remove the stun: Server.

**Comment by streamer45** [comment]
Closing this for now but feel free to comment further if something is not working as expected.
