### ISSUE TITLE
Multiple 'join call' clicks needed

### ISSUE THREAD

**Issue by H-B-Schmidt** [mattermost/mattermost-plugin-calls#142]
A user has to repeat 'join call' multiple times before the call is finally joined. I think it is the case when the configured TURN server is required for communication

**Comment by streamer45** [comment]
I think this is likely some lag as we don't currently have an interface to display the "connecting..." state (planned in [MM-42429](https://mattermost.atlassian.net/browse/MM-42429)). Clicking more than once doesn't really do anything unless the client disconnected previously. Client console logs would be helpful to verify this.

**Comment by H-B-Schmidt** [comment]
It is most likely a disconnect. I asked the user to wait instead of clicking multiple times and it did not work. 
The user initiating the call can see a brief connect which is immediately terminated for each failed attempt.

**Comment by H-B-Schmidt** [comment]
User updated his desktop client and the problems seems to be fixed.
