### ISSUE TITLE
This plugin failed to start

### ISSUE THREAD

**Issue by lwtzyz** [mattermost/mattermost-plugin-calls#165]
This plugin failed to start. unable to start plugin: com.mattermost.calls: fork/exec plugins/com.mattermost.calls/server/dist/plugin-darwin-amd64: no such file or directory
for some reason, i trying to deploy this plugin in my mac, but i got message above.is that plugin available on mac?or it's something was lost when i installation.

**Comment by streamer45** [comment]
Hi @lwtzyz,

we only officially support Linux (amd64) builds hence why the binary for OSX is missing from the official release. If this is for test purposes you could build it locally from this repository (`make dist` command) and that should generate a valid binary for MacOS as well.
