### ISSUE TITLE
No more ringing after upgrading to Mattermost 7.2

### ISSUE THREAD

**Issue by perkooo** [mattermost/mattermost-plugin-calls#183]
I recently upgraded Mattermost to v7.2, and we noticed that we don't hear anymore the ring (caller or receiver).

Otherwise, calls are properly working.

Anyone else is having this issue with the Mattermost 7.2 version?

**Comment by streamer45** [comment]
Hi @perkooo, what ringing sound are you referring to? This plugin doesn't really provide any additional notification when someone calls you but solely relies on the existing channel wide notification system when a new message gets posted.

There's been some discussion to add a more explicit notification in https://github.com/mattermost/mattermost-plugin-calls/issues/125 but in your case I must assume something has changed somewhere else with either user or channel preferences.

**Comment by perkooo** [comment]
Ok my bad, I thought there was a constant ringing when calling but it's not the case, just the initial sound notification from Mattermost.

It would be a great feature! Will follow #125 :)

Thanks
