### ISSUE TITLE
Build for arm64 arch - For Pi 4B

### ISSUE THREAD

**Issue by kirtan403** [mattermost/mattermost-plugin-calls#203]
I'm running the Mattermost arm64 build with docker on Pi 4B successfully (ref: ). However, when I try to enable the Calls plugin from the Marketplace, it fails to start with the error:

```
This plugin failed to start. unable to start plugin: com.mattermost.calls: fork/exec plugins/com.mattermost.calls/server/dist/plugin-linux-arm64: no such file or directory
```

How can I build this plugin for the arm64, any details someone can provide to guide me?

**Comment by kirtan403** [comment]
I just checked, Playbooks plugin is working fine. It includes arm64 arch.

https://github.com/mattermost/mattermost-plugin-playbooks/

**Comment by kirtan403** [comment]
I just checked this:

https://github.com/mattermost/mattermost-plugin-calls/blob/main/Makefile#L115

Can we update this?

**Comment by streamer45** [comment]
Hi @kirtan403 , we can add it but as mentioned in [similar requests](https://github.com/mattermost/mattermost-plugin-calls/issues/45) we won't be able to support it officially. With that understood, I am happy to create a ticket to address this.

**Comment by kirtan403** [comment]
@streamer45 Thanks, yes I can understand. Adding it to the release bin will be really helpful. Same as playbooks add it. You can also mention it in the readme.

**Comment by kirtan403** [comment]
@streamer45 What could be the ETA for this to be available in the next release? I was planning to install it on my server. So just wanted to know the approximate date.
