### ISSUE TITLE
Mic Issue since updating to v0.9.0 from the marketplace

### ISSUE THREAD

**Issue by jonwsoto** [mattermost/mattermost-plugin-calls#221]
Seems that when I start a call, the other party does not hear me until I begin to share my screen. After this, I can stop sharing and the mic will work no problem. Seems to be affecting all the browsers.

**Comment by streamer45** [comment]
Thanks @jonwsoto, 

I had a look at the logs you sent me and everything seems fine on your end as the client is transmitting the voice track as expected. I suspect the problem could be on receiving side although I'd need some logs from that client (the one unable to hear you) to debug further. 

Could you confirm previous version was working ([v0.8.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.8.1)) for the same clients?

**Comment by jonwsoto** [comment]
I am on hosting with docker on a Synology NAS. The admin account is logged in on macOS version 12.4 using chrome browser version 106.0.5249.119. I have reverse proxy setup and cloudflare CDN. I have the UDP port exposed outside of the reverse proxy and defined the ICE host override to use my domain. 

The receiving side I am on iPhone 13 iOS 16.0.2. 

Seems everything was working well on v0.8.1. 

I feel as though there was a day where there was no issue with the voice coming through but it has since recurred. Can’t tell if this is something I am overlooking vs a bug. Today in my testing, I am still having the issue. I have to start presentation mode and then the sound comes through no problem and remains after ending the presentation mode.

**Comment by streamer45** [comment]
Thanks for the additional info. I have a feeling this may be an issue on the mobile side then. What Mattermost app version are you running on iOS? We very recently fixed [a bug](https://github.com/mattermost/mattermost-mobile/pull/6662) that could cause what you are describing.

**Comment by jonwsoto** [comment]
I am running the latest it looks like. v1.55.1

**Comment by streamer45** [comment]
> I am running the latest it looks like. v1.55.1
> 
> On my iPhone I tested using the safari browser instead of the app. And it appears through the browser it works well, no voice issues. It may be possible it’s the app, any way to send you logs for this?

If it's the issue I mentioned earlier you'll need to install v1.56 which should be out soon (next week I am thinking).

**Comment by streamer45** [comment]
This should be fixed in the upcoming 1.56 release coming on Nov. 16th
