### ISSUE TITLE
Full-screen in calls causes issues

### ISSUE THREAD

**Issue by francislavoie** [mattermost/mattermost-plugin-calls#251]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

After full-screening and un-fullscreening a call (bottom-right button in the call), the app's menu bar (File/Edit/View) appears at the top, which pushes all of the rendered interface down however many pixels the menu bar takes up.

Also, while full-screened, the custom menu bar (three-dots menu + servers picker etc) is still at the top of the screen. I think it should not be there when full-screen because it cuts into the total viewable height of the call. It should be hidden when full-screen.

**Environment**
- Operating System: Linux, PopOS (debian/ubuntu-based)
- Mattermost Desktop App version: 5.1.1 
- Mattermost Server version: 7.2.0 

**Steps to reproduce**

- Start a call with someone
- Have them screen share
- Click Pop-out
- Click Full-screen 
- See that the custom menu bar is shown (point number 2)
- Close Full-screen
- See that the menu bar appeared (point number 1)

**Comment by devinbinnie** [comment]
Moved this issue over to calls for now.

**Comment by streamer45** [comment]
I am closing this as we stopped supporting this way of displaying the calls expanded view on desktop. I'd strongly recommend to update to the latest 5.3.x release which is now available.

**Comment by francislavoie** [comment]
I just installed `Version 5.3.1-rc.1 commit: c39d197`, this is not fixed. Full-screening the call causes the menu items to appear, which offsets the entire UI.

**Comment by streamer45** [comment]
@francislavoie I suspect you may be running an out-of-date plugin version since the full screen view has been completely replaced with a new window. Do you know which version of Calls you are running on the Mattermost server you are connecting to?

**Comment by francislavoie** [comment]
We're on server `Mattermost Version: 7.5.2`, since we're using it via Gitlab.

**Comment by streamer45** [comment]
Right, upgrading to the latest ESR (`7.8.x`) should fix this as the new implementation requires some plugin changes as well.

**Comment by francislavoie** [comment]
Okay, nice, we've upgraded to server `7.8.2` and I do see the new call widget. Big improvement for fullscreen functionality especially since it opens in a separate window, better for multi-tasking. Thanks for that.

I did notice one minor regression though. The call widget opens in the bottom left (like before) but now it's wider than it used to be, so it isn't completely contained within the sidebar nav pane anymore, it covers part of the bottom left of the conversation pane, covering the letter `W` from the text box. This is using Desktop version `Version 5.3.1 commit: 2c3d80f` on Linux (using the `.deb`).

![image](https://user-images.githubusercontent.com/2111701/230425356-7306433b-b2d0-4b3a-8d6d-8641d9ba18f6.png)

Should I open a new issue for this? Or is it known?

**Comment by streamer45** [comment]
Cool, glad to know it's working better. 

> ![image](https://user-images.githubusercontent.com/2111701/230425356-7306433b-b2d0-4b3a-8d6d-8641d9ba18f6.png)
> 
> Should I open a new issue for this? Or is it known?

Yaah, it's actually a know issue which we fixed but not released yet. Let me see if I can get it in the next release which is coming out soon.

**Comment by francislavoie** [comment]
Great to hear, thanks!
