### ISSUE TITLE
Calls always drop after 15 seconds with error "Connection Failed"

### ISSUE THREAD

**Issue by motlaghreyhan** [mattermost/mattermost-plugin-calls#257]
## Summary of issue

Mattermost calls will stay connected for only 15 seconds, at which point a 
`Connection failed
There was an error with the connection to the call. Try to re-join the call. Check the troubleshooting section if the problem persists.`
 message will pop up and the call will disconnect. During that 15 seconds nothing can be heard. I see `call state is missing from channel state` error from the server logs, but not much else. 
 
 `{"timestamp":"2022-12-02 12:46:35.695 -05:00","level":"error","msg":"callback failed: call state is missing from channel state","caller":"app/plugin_api.go:974","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleLeave websocket.go:381"}`

## How to encounter/reproduce issue

Our mattermost setup is a bit odd. We have a proxy node that accepts all traffic, and uses nginx to forward all mattermost traffic to the mattermost VM (running on rhel8). Everything other than calls works fine, I've also tried forwarding port 8443 with iptables to the VM, but with no luck. 

We had it fully functioning for a short while (woke up one day and it was spontaneously working, cannot explain why), held 1+ hour calls no problem, however after a server restart was needed everything broke again and calls won't last more than 15 seconds. I've attached all relevant config files and logs (replaced our domain with {{domain}}), not sure if this is a configuration issue on my end, or a bug with using a subdomain. Any help would be appreciated!

[proxynginx.txt](https://github.com/mattermost/mattermost-plugin-calls/files/10143140/proxynginx.txt)
[hostnginx.txt](https://github.com/mattermost/mattermost-plugin-calls/files/10143149/hostnginx.txt)
[mmconfig.txt](https://github.com/mattermost/mattermost-plugin-calls/files/10143159/mmconfig.txt)
[proxyiptables.txt](https://github.com/mattermost/mattermost-plugin-calls/files/10143199/proxyiptables.txt)

**Comment by streamer45** [comment]
@motlaghreyhan 15 seconds is the timeout we have in place for the media path connectivity so the call is not really connecting even though the UI shows up. This is the number one issue when setting up Calls since it requires some extra networking setup.

The reason it may have randomly worked is possibly due to STUN which is a way some clients are able to bypass NAT devices and establish connectivity but it's not going to work reliably as it greatly depends on the network infrastructure between client and server.

Coming back to the issue at hand, ideally you'd want the media (UDP based) path to go straight to the Mattermost instance which should have its own client facing IP address. 

I see you have configured the `icehostoverride` setting but I suspect that's pointing to the load balancer (`nginx`) rather than the Mattermost instance behind it. This could be the key problem as I don't see any configuration there to forward the media packets which go through a separate port (8443) and totally different protocol (UDP).

Overall my suggestion would be to try and create a direct path to the Mattermost instance by exposing an IP address and open the necessary UDP port. If this is unfeasible then you are left with the option to proxy the UDP traffic through `nginx` with something special config like this:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
}

http {
    ...
}

stream {
  upstream backend_udp {
    server (mattermost host):8443;
  }

  server {
                listen                  8443 udp rcvbuf=4194304 sndbuf=4194304;

                proxy_responses         864000000;
                proxy_timeout           30s;
                proxy_next_upstream     on;
                proxy_next_upstream_timeout 600s;
                proxy_next_upstream_tries   3;
                proxy_pass              backend_udp;
  }
}
```

**Comment by motlaghreyhan** [comment]
Thanks for the response! Unfortunately with our setup, we're a public university and I'd like to avoid having to get our IT department involved to give new machines open ports, there's a lot of red tape around that. It may come to that eventually but I'd like to try proxying the traffic through our one public facing node first if that's possible. 

I did end up adding the the `stream` section of the block you send me above to our nginx.conf, however I'm still getting the same errors. It may be because I tried putting it after the http{} section like you have above, but when I do that nginx errors out with `nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/nginx.conf:112`. However if I put it right before the http{} nginx doesn't complain. Is this affecting things? 

I can confirm that the port is showing open, and that it seems to be seeing the right services. Also, it didn't seem necessary, but do I need anything in the mattermost host's nginx.conf or can that be left alone? I've also attached what looked like relavant logs from the mm server in case that helps.

Starting Nmap 7.93 ( https://nmap.org ) at 2022-12-03 13:07 EST
Nmap scan report for {{domain}} ({{ip}})
Host is up (0.0050s latency).

PORT     STATE         SERVICE
8444/udp open|filtered pcsync-http

Nmap done: 1 IP address (1 host up) scanned in 0.29 seconds



{"timestamp":"2022-12-03 13:50:31.070 -05:00","level":"debug","msg":"websocket.NextReader: client side closed socket","caller":"app/web_conn.go:827","user_id":"mpcnxd3riifab8s9t1844me8ah"}
{"timestamp":"2022-12-03 13:50:31.071 -05:00","level":"debug","msg":"leave message","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).WebSocketMessageHasBeenPosted websocket.go:666","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh"}
{"timestamp":"2022-12-03 13:50:31.071 -05:00","level":"debug","msg":"handleLeave","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleLeave websocket.go:346","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","channelID":"jtajpe647bfbtmoq4offhooxwc"}
{"timestamp":"2022-12-03 13:50:31.071 -05:00","level":"debug","msg":"user left call","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleLeave websocket.go:353","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","channelID":"jtajpe647bfbtmoq4offhooxwc"}
{"timestamp":"2022-12-03 13:50:31.071 -05:00","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:165","method":"GET","url":"/mm/api/v4/websocket","request_id":"8ug6gbncmjyiuetq5o3xb54mhw"}
{"timestamp":"2022-12-03 13:50:31.072 -05:00","level":"debug","msg":"closing ws channel for session","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).OnWebSocketDisconnect websocket.go:280","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","channelID":"jtajpe647bfbtmoq4offhooxwc"}
{"timestamp":"2022-12-03 13:50:31.073 -05:00","level":"debug","msg":"closeRTCSession","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).closeRTCSession websocket.go:711","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","channelID":"jtajpe647bfbtmoq4offhooxwc"}
{"timestamp":"2022-12-03 13:50:31.073 -05:00","level":"debug","msg":"peer connection closed","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"yoaw76mcd3yd8d1knxrehgqkgh"}
{"timestamp":"2022-12-03 13:50:31.073 -05:00","level":"debug","msg":"ice closed","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Debug log.go:80","sessionID":"yoaw76mcd3yd8d1knxrehgqkgh"}
{"timestamp":"2022-12-03 13:50:31.073 -05:00","level":"debug","msg":"removing session from state","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).removeSession session.go:228","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","originalConnID":"yoaw76mcd3yd8d1knxrehgqkgh"}
{"timestamp":"2022-12-03 13:50:31.088 -05:00","level":"debug","msg":"removing session from state","caller":"app/plugin_api.go:968","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).removeSession session.go:228","userID":"mpcnxd3riifab8s9t1844me8ah","connID":"yoaw76mcd3yd8d1knxrehgqkgh","originalConnID":"yoaw76mcd3yd8d1knxrehgqkgh"}
{"timestamp":"2022-12-03 13:50:31.089 -05:00","level":"error","msg":"callback failed: call state is missing from channel state","caller":"app/plugin_api.go:974","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).handleLeave websocket.go:381"}

**Comment by streamer45** [comment]
Could you share the updated nginx config, with the added stream block?

What I'd suggest to do in order to verify connectivity is the following:

1. Temporarily disable the Calls plugin.
2. On the Mattermost instance run `echo "server msg" | nc -l -u 0.0.0.0 8443`. Change the port number to whatever you have configured.
3. On a client instance run `echo "client msg" | nc -u NGINX_HOST 8443`. Change `NGIN_HOST` with the client facing IP address/hostname of your nginx server (what you'd set as `icehostoverride`)
4. Check that the messages are correctly received on both sides.

**Comment by motlaghreyhan** [comment]
Thanks for this, definitely helped me troubleshoot our problem a bit further. Looks like our IT dept has different firewall settings on each of our nodes and their firewall looks to be blocking 8443/udp. I've tried routing the calls through one of our hosts that has no firewall on their end, however I'm still seeing the same results. I've set the icehostoverride to the new domain, and verified that the ports are open. I should add that these packets are being passed with iptables and not nginx. 

#mattermost
-A PREROUTING -d {{publicip}}/32 -p udp -m udp --dport 8443 -j DNAT --to-destination 192.168.4.137:8443
-A PREROUTING -d 192.168.1.13/32 -p udp -m udp --dport 8443 -j DNAT --to-destination 192.168.4.137:8443
-A POSTROUTING -d 192.168.4.137/32 -p udp -m udp --dport 8443 -j SNAT --to-source 192.168.1.13

[root@mattermost ~]# echo "server msg" | nc -l -u 0.0.0.0 8443
client msg

[rmotlagh@Reyhans-MBP:~]$ echo "client msg" | nc -u {{newdomain}} 8443
server msg

"com.mattermost.calls": {
                "allowenablecalls": false,
                "allowscreensharing": true,
                "defaultenabled": true,
                "icehostoverride": "{{newdomain}}",
                "iceserversconfigs": "",
                "maxcallparticipants": 0,
                "rtcdserviceurl": null,
                "serversideturn": true,       ## (I've tried both true and false here)
                "turncredentialsexpirationminutes": 1440,
                "turnstaticauthsecret": "",
                "udpserverport": 8443
            },


Is this an unsupported configuration? I imagine since the icehostoverride exists at all, this should work, but I'm seeing the exact same 15 second disconnection behavior. 

Thanks again for all the help!

**Comment by streamer45** [comment]
It sounds like it should work but to help further let me understand a bit more about your setup. Is `192.168.4.137` the Mattermost instance running Calls? What about `192.168.1.13`? If you can sketch a very simple diagram it would be helpful.

To debug further I'd suggest to temporarily run Mattermost with the `PION_LOG_TRACE=ice` environment flag set. This will produce some lower level logs when joining calls which could be helpful to identify the issue.

Also, please feel free to reach out internally on our [community server](https://community.mattermost.com) so you can share logs privately. You can find me as `@claudio.costa`.

**Comment by streamer45** [comment]
This was resolved internally. Huge thanks to @motlaghreyhan for working with me on this.

One important bit to note which I'll add to the documentation is that the `icehostoverride` setting ultimately needs to be an IP address and if a hostname is used instead then a resolution happens on the server (Mattermost) side. This can prove to be an issue as the resolved IP could be totally different from the client facing one.

**Comment by rindelit** [comment]
For some time now, when trying to call Mattermost 1 on 1 or in a group, an error occurs after 15 seconds:

**There was an error with the connection to the call. Try to re-join the call.**

Moreover, the problem does not repeat regularly, but periodically. Sometimes 1 on 1 or group calls go well, sometimes not at all.

Knowledgeable colleagues point out possible problems with STUN, but it is not entirely clear what exactly needs to be configured.

Mattermost version: 9.4.1. Calls plugin version: com.mattermost.calls-0.23.1

Please suggest how to solve the problem. From the above correspondence it is not entirely clear what needs to be done. Thank you.
