### ISSUE TITLE
Install Documentation Missing : RTC Port Open - Fixes Calls disconnection after 15 Seconds

### ISSUE THREAD

**Issue by mdowais** [mattermost/mattermost-plugin-calls#260]
Hello,

The links in the ReadMe dont take to appropriate Install Guide.

Importantly it doesn't say about RTC Port Opening which is Necessary for making calls.

The Following can be added to ReadMe:

RTC port has to be opened for Calls, else the call will drop automatically after a hard limit of 15 Seconds. By default it is 8443 and can be configured in the settings page. If everything works you will see "rtc connected" in Browser Console.

If using Docker-Compose add following under ports

```YAML
    ports:
      - 8443:8443/udp
      - 8443:8443/tcp
```

May fix https://github.com/mattermost/mattermost-plugin-calls/issues/257

**Comment by streamer45** [comment]
Hi @mdowais , thanks for the feedback. 

We need to update the README as the official documentation can be found at https://docs.mattermost.com/channels/make-calls.html and https://docs.mattermost.com/configure/calls-deployment.html which lists the basic requirements.

I created an internal ticket ([MM-48853](https://mattermost.atlassian.net/browse/MM-48853)) for taking care of this improvement.

**Comment by streamer45** [comment]
I've updated the README to link to the official documentation which mentions all the requirements and also updated our docker compose files in https://github.com/mattermost/docker to allow for the required port.

Will close this now but feel free to re-open if you have more feedback, thanks!
