### ISSUE TITLE
Calls fail in Firefox Linux when FIPS is enabled

### ISSUE THREAD

**Issue by dawilluz** [mattermost/mattermost-plugin-calls#290]
Joining or starting a call fails when using Linux Firefox with FIPS mode enabled on the client OS.  This was verified to be a FIPS issue by rebooting and disabling FIPS in the GRUB kernel screen, which allows Firefox to make calls again.  The issue occurs when using built-in STUN or using a TURN server with coturn (4.6.1-1).

Errors:
- Mattermost simply states "Connection Failed"
- The Firefox consol reports the following
```
com.mattermost.calls:  join ack received, initializing connection
com.mattermost.calls: peer error DOMException:  The Operation failed for an operation-specific reason
com.mattermost.calls: disconnect
Invalid URI.  Load of media resource failed
```

Environment:
Mattermost 7.5.1
Server OS: Rocky 8 / 4.18.0-425.3.1
Client OS:  CentOS 7.9.2009 / 3.10.0-1160.81.1
Firefox:  102.6.0esr

**Comment by streamer45** [comment]
I did a little research on this and I am fearing it may be a problem at Firefox or even OS level, or at least with the used SSL library. Not sure how much they apply to your OS but these are a couple of references to potentially related issues:

https://bugzilla.redhat.com/show_bug.cgi?id=2013119
https://bugzilla.redhat.com/show_bug.cgi?id=2012050

**Comment by streamer45** [comment]
Closing this as I don't think there's much we can do from this ide. It's very likely either a browser limitation or system bug/misconfiguration. Please let us know if this is still an issue.
