### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by creeper-0910** [mattermost/mattermost-plugin-calls#302]
I noticed that there was a mattermost translation server after I created the translations for the calls.
I would like to contribute to the translation, but I can't find the translation of calls on the translation server.
Where can I upload the translation?
Sorry for the inconvenience.

**Comment by streamer45** [comment]
Hi @creeper-0910, we are not yet supporting internationalization for Calls but it's on the roadmap so as soon as we do I'll make sure to let you know as a contribution would be highly welcome. /cc @justinegeffen

**Comment by creeper-0910** [comment]
Okay, thank you!
I will try to help with other translations of mattermost in the meantime.
I wish you all the best in the development of mattermost!

**Comment by justinegeffen** [comment]
Thanks so much for your contribution, @creeper-0910! Please come and join our [Localization channel](https://community.mattermost.com/core/channels/localization) where you can connect with members of our translation community and they can help guide you through this process. :)

**Comment by creeper-0910** [comment]
Thank you!
I joined the server today👍

**Comment by streamer45** [comment]
@creeper-0910 Localization support for calls has been added last week. New locales can be now contributed. Please consider joining https://community.mattermost.com/core/channels/localization to coordinate. Thanks :)

**Comment by creeper-0910** [comment]
Thanks for the good news!
I'll get right on it👍

**Comment by streamer45** [comment]
Closing this as translations support has been added and new translations can be contributed through our weblate server.
