### ISSUE TITLE
Starting a call leaks full name of creator when full names are disabled on a server level

### ISSUE THREAD

**Issue by Morthy** [mattermost/mattermost-plugin-calls#314]
When "Show Full Name" is set to false in the System Console under "Users and teams", starting a call reveals the full name of the creator to all members of the channel while the call is ongoing.

![image](https://user-images.githubusercontent.com/5537959/215997548-e96f9b5c-f6c5-48ae-966d-a0442efdc0b5.png)

I believe the problem is here: https://github.com/mattermost/mattermost-plugin-calls/blob/12bd8e9a05b1908d96036ab249f9ffae4bc9803a/server/plugin.go#L276

I reported the same issue in another plugin last year, and they solved it like this: https://github.com/matterpoll/matterpoll/blob/master/server/plugin/plugin.go#L165

**Comment by streamer45** [comment]
Thanks for reporting this @Morthy. I created an internal ticket (https://mattermost.atlassian.net/browse/MM-50234) to track this and fix it soon.
