### ISSUE TITLE
com.mattermost.call not loading in system console 

### ISSUE THREAD

**Issue by rajmaskey** [mattermost/mattermost-plugin-calls#344]
As a system admin, it's not loading the plugin control dashboard here is a picture for reference 
log: `Feb 22 21:47:59 {"timestamp":"2023-02-22 16:02:59.686 Z","level":"error","msg":"failed to read RTP packet","caller":"app/plugin api.go:976","plugin_id":"com.mattermost.calls","origin":"main.(*logger).Error log.go:103","error":"EOF","sessionID":"8woo5ta66pywubtray3xphj4ia"}`

![image](https://user-images.githubusercontent.com/76200506/220686550-5ce73768-3536-43f6-a217-f10e912a76d6.png)

**Comment by streamer45** [comment]
@rajmaskey I think it would be more helpful if you could share the JS console logs when visiting the page. Also, does the same happen with `/admin_console/plugins/plugin_com.mattermost.calls`? The screenshot you posted is pointing to the apps plugin.

**Comment by jackxb** [comment]
My plugin settings don't display too, but if I turn off the plugin, the settings start working

**Comment by jackxb** [comment]
I uninstalled the plugin and reinstalled it from the Marketplace, everything worked.

**Comment by dvnrsn** [comment]
There was an update available on the marketplace. That resolved the react errors for me.
<img width="223" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/9112811/6598ddfd-d727-4f9f-a6df-cfbb906e50e6">
