### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'rtcdserviceurl')

### ISSUE THREAD

**Issue by komkomissarov** [mattermost/mattermost-plugin-calls#355]
Hello!
I just installed self-hosted version of MM in docker, Team edition (no license). 
When I go in System Console > Plugins > Calls  it's just white screen. 
![image](https://user-images.githubusercontent.com/17730130/223937148-9082c2c6-6384-475d-8aa3-94c51644d3af.png)
```
handleError::  Uncaught TypeError: Cannot read properties of undefined (reading 'rtcdserviceurl')
```
Postgres alpine 13
nginx alpine
MATTERMOST_IMAGE=mattermost-team-edition
MATTERMOST_IMAGE_TAG=release-7.9

The only changes in env file I made is path to dir (logs, data etc) that mounts in container.
Everything else, like nginx conf is untouched from repo https://github.com/mattermost/docker

Calls itself seems to be working, three of us can enter the call, show ours screens. 
It seems problem is on calls plugin settings page. 

I've tried it from Chrome, Firefox, YandexBrowser, Windows Desktop app.

**Comment by komkomissarov** [comment]
Tried install 0.14.0 and get error when uploading archive. 
Reinstall 0.13.0 from market and its works fine.

**Comment by steccas** [comment]
I'd like to reopen the issue, I'm exactly in the same situation.

**Comment by komkomissarov** [comment]
Did you try to reinstall calls plugin?
