### ISSUE TITLE
Please stop re-tagging repostiory!

### ISSUE THREAD

**Issue by alerque** [mattermost/mattermost-plugin-calls#397]
Once you publish a tag, Please stop silently deleting and republishing it. A v0.15.4 tag went out the other day (and I packaged it for Arch Linux and put it in production), then a couple days later it disappeared and was reposted an v0.15.4. I understand the tag naming was probably in error, but sometimes when you make a mistake you just need to roll with it. Make the next release v0.15.5 or something.

Now even worse even the new v0.15.0 tag got removed and reposted *again*. This screws up all sorts of downstream package verification systems and makes auditing our supply chain really hard!

Please stop re-tagging!

**Comment by streamer45** [comment]
@alerque I am sorry to hear about these issues. Could you help me understand how a new tag/release on this side is causing problems on yours? The official way to get this plugin is through [Mattermost server](https://github.com/mattermost/mattermost-server) which follows a much stricter release process. Are you actually publishing a new MM build each time we tag something in here?

**Comment by streamer45** [comment]
Closing this for now as there's no action to be taken. Please let us know if we can help with anything else.

**Comment by alerque** [comment]
> . Are you actually publishing a new MM build each time we tag something in here?

No, just publishing a new plugin package. I am one of the maintainers for the Mattermost package on Arch, and the way we have it setup (as most of the webapps we package) is that the system files are only writable by the package. Mattermost doesn't have permission to just drop new files onto the system at run time unless users explicitly modify their system (which some do of course) to open up the permissions. Installing plugins is also done with the system package manager. Hence why this is packaged: people can install it (and have it updated) with their system packages.

So yes every time this gets tagged I have to look into updating the packaging, but only for this plugin not for MM itself (of course min/max version bounds are important too).

**Comment by streamer45** [comment]
Thanks for context. Will try to be more careful then :)
