### ISSUE TITLE
Update plugin from Marketplace

### ISSUE THREAD

**Issue by jackxb** [mattermost/mattermost-plugin-calls#403]
Hi,
Under Release I see a new version (0.15.1), but it is not in the Marketplace (I see 0.14.0), how can I update the plugin?

**Comment by cpoile** [comment]
Hi @jackxb, can you show me a screen cap of your marketplace searching for `calls`? I can see it on my local installation: 
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1490756/231794823-443c0635-2f00-4c33-ace7-fc7c0f7c3f8a.png">

**Comment by cpoile** [comment]
@jackxb I think you'll need to `Enable Remote Marketplace` if you want to use the marketplace update feature.

**Comment by jackxb** [comment]
@cpoile thanks, I'll try it now.

**Comment by jackxb** [comment]
@cpoile thank you so much! I can see the update now.
![Screenshot 2023-04-13 at 6 03 51 PM](https://user-images.githubusercontent.com/12335003/231802327-1fcb4e47-b72d-41ad-9005-25960692eb29.png)

**Comment by cpoile** [comment]
@jackxb Awesome, glad I could help.
