### ISSUE TITLE
add continous ringtone for calls

### ISSUE THREAD

**Issue by jagiella** [mattermost/mattermost-plugin-calls#427]
**Mattermost Version**
7.1.8 and 7.10 (self-hosted / docker)

**Plugin Version**
0.10.0 BETA and 0.15.1

**Describe the issue**
When starting calls with the Calls-Plugin (not Jitsi) usually nobody joins as people get a single notification which is easily missed. So that makes the whole calls feature (which is awesome by the way!!) useless as everybody has to be contacted by other means (phone) to make them aware of the meeting.

It would be nice to have a continous ringtone notifying everybody in the same channel of the active call(s) until they join or actively mute the ringtone / refuse the call. https://github.com/mattermost/mattermost-plugin-jitsi/issues/233

**Comment by streamer45** [comment]
Thanks for the feedback @jagiella . Part of this is being actively worked on to address https://github.com/mattermost/mattermost-plugin-calls/issues/125

**Comment by streamer45** [comment]
We are finally releasing this functionality (thanks @cpoile for the incredible contribution!). 

Please keep in mind it's an experimental feature which needs to be explicitly turned on from the plugin settings. 

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/1832946/3ef4e68c-a81f-4015-a508-015c73fd6c55)

Also note that it comes with some limitations which will be addressed in the next version (e.g. mobile support).

Feel free to report any issues or leave feedback. Thank you all for your patience!
