### ISSUE TITLE
how to access the list of participants?

### ISSUE THREAD

**Issue by Guoxweii** [mattermost/mattermost-plugin-calls#433]
I have set up a Mattermost service using Docker Compose with version number 7.1.9. Is it possible for me to access the list of participants in a voice call through the API?

We are a remote work company, and we need to scan the list of participants in the work voice channel every day to track attendance of employees.

**Comment by streamer45** [comment]
Hi @Guoxweii, 

We have plans to provide some basic statistics on calls usage to system admins, however we haven't implemented any of this yet.

Also, we don't really support public API access either. That said, we expose some information for internal purposes that you may be able to use to achieve what you want, at least partially. 

To find current active calls you can make an HTTP GET request to:

```
/plugins/com.mattermost.calls/channels
```

Also, given a channel id, you can make an HTTP GET request to:

```
/plugins/com.mattermost.calls/channel_id
```

If there's a call ongoing the JSON object returned will contain a `call` object with all the call information, including a `users` array with the list of user ids of the participants, e.g.:

```json
{
	"channel_id": "kpry8998bjn8uf516bmhnq1rua",
	"enabled": true,
	"call": {
		"id": "4osohhcqjifgfjpfibgoz1b3fr",
		"start_at": 1684216957271,
		"users": ["6ibcoo1xpi8dze7a9kma9y4uga"],
		"states": [{
			"unmuted": false,
			"raised_hand": 0
		}],
		"thread_id": "bsmxsnwpyjyj8qhc6w55by7e6w",
		"post_id": "bsmxsnwpyjyj8qhc6w55by7e6w",
		"screen_sharing_id": "",
		"owner_id": "6ibcoo1xpi8dze7a9kma9y4uga",
		"host_id": "6ibcoo1xpi8dze7a9kma9y4uga"
	}
}
```

The important limitation here is that you can only fetch calls the user making the request can access. So if you don't have permission to a certain channel (e.g. DM) you won't be able to fetch call information for those.

**Comment by Guoxweii** [comment]
Thank you very much, I will try it immediately.

**Comment by streamer45** [comment]
Closing this for now. Please let us know if you need further support.
