### ISSUE TITLE
Cant disable test mode in call settings

### ISSUE THREAD

**Issue by adamfasullo** [mattermost/mattermost-plugin-calls#434]
For some reason, when I try to disable test mode on my call settings page, it still wont allow non-admin users the ability to place calls. They receive an error asking them to contact the system admin. 

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5818381/44ec7bc1-3820-4399-909e-ef685979b4b5)

Is what is displayed when initiating a call as admin. 

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5818381/9d7580aa-0611-4465-88ad-53442eacf348)

Is what the setting is currently set to. 

Running MM Omnibus.

**Comment by streamer45** [comment]
@adamfasullo Could you send the response of fetching `/plugins/com.mattermost.calls/config`? Clients may simply need to reload the page/app before they can start calls once the setting has been turned off.

**Comment by adamfasullo** [comment]
@streamer45 thanks for the reply. I checked the config from the url: 

{"ICEServers":null,"ICEServersConfigs":[{"urls":["stun:stun.global.calls.mattermost.com:3478"]}],"AllowEnableCalls":true,"DefaultEnabled":false,"MaxCallParticipants":0,"NeedsTURNCredentials":false,"AllowScreenSharing":true,"EnableRecordings":false,"MaxRecordingDuration":60,"EnableSimulcast":false,"sku_short_name":"starter"}

which is different to the configuration settings I have for the plugin: 

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5818381/3c0678b8-cd45-4912-ac92-84e67da17731)

The stun settings are also not reflected along with the test settings. I have checked mmctl control as well to see the settings listed there (as omnibus does not use config.json) 

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5818381/33e88a78-4334-4719-b347-fdd291d151ff)

And the settings are correct here. It is like it's not reading my configs and rather passing the defaults instead. Any ideas?

**Comment by adamfasullo** [comment]
Additionally there seems to be another person mentioning the same issue in the mattermost community chat:
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/5818381/cb603995-0c8e-4911-87ad-6cf885af2be8)

**Comment by streamer45** [comment]
Thanks @adamfasullo, a couple of questions:

1. What MM version are you running?
2. Could you share server logs around the time you try to save these settings?

**Comment by adamfasullo** [comment]
@streamer45 these are the two log entries i see when saving the config form. 

==> /var/log/nginx/error.log <==
2023/05/24 07:00:11 [warn] 2434#2434: *6438 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000010, client: 162.158.189.170, server: xxxx, request: "PUT /api/v4/config HTTP/2.0", host: "xxx"

==> /var/log/mattermost/mattermost.log <==
{"timestamp":"2023-05-24 07:00:11.752 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:436","tag_value":"sysconsole_write_*_read"}
{"timestamp":"2023-05-24 07:00:11.764 Z","level":"info","msg":"Loaded system translations","caller":"i18n/i18n.go:132","for locale":"en","from locale":"/opt/mattermost/i18n/en.json"}

**Comment by streamer45** [comment]
Thanks @adamfasullo , can't see anything of note there, also settings appear to be saved correctly on the server side. A couple of questions:

1. What Mattermost and Calls plugin versions are you currently running?
2. Could you confirm that the expected settings are available when loading `/api/v4/config` ? (you need to load that from a system admin account)

**Comment by adamfasullo** [comment]
@streamer45 Running MM 7.10.2 (Latest Version) and calls 0.16

Those settings are correct when using /api/v4/config. So it seems they are only coming incorrectly when reading them from the calls/config path


"Plugins":{"com.mattermost.calls":{"allowscreensharing":true,"defaultenabled":true,"enablerecordings":false,"enablesimulcast":false,"icehostoverride":"","iceserversconfigs":"[\n      {\n        urls: \"stun:a.relay.metered.ca:80\",\n      },\n      {\n        urls: \"turn:a.relay.metered.ca:80\",\n        username: \"xxxxxxx\",\n        credential: \"PU/xxxxxxx\",\n      },\n      {\n        urls: \"turn:a.relay.metered.ca:80?transport=tcp\",\n        username: \"xxxxxx\",\n        credential: \"xxxxxxx\",\n      },\n      {\n        urls: \"turn:a.relay.metered.ca:443\",\n        username: \"xxxxxxxxx\",\n        credential: \"PU/xxxxxxx\",\n      },\n      {\n        urls: \"turn:a.relay.metered.ca:443?transport=tcp\",\n        username: \"xxxxxx\",\n        credential: \"PU/xxxxxx\",\n      },\n  ]","jobserviceurl":null,"maxcallparticipants":0,"maxrecordingduration":60,"recordingquality":"medium","rtcdserviceurl":null,"serversideturn":false,"turncredentialsexpirationminutes":1440,"turnstaticauthsecret":"","udpserveraddress":"","udpserverport":8443}

**Comment by streamer45** [comment]
Alright thanks. Something is clearly wrong then, I'll open an internal ticket and try to reproduce. Will give an update here when I have one.

**Comment by streamer45** [comment]
Closing this as the issue was resolved. Problem was that the `iceserversconfigs` setting contained invalid JSON. We'll work on a better way to spot these issues from the UI to avoid saving invalid data.
