### ISSUE TITLE
Mattermost Call

### ISSUE THREAD

**Issue by alifiroozi80** [mattermost/mattermost-plugin-calls#440]
Hello everyone,
I’ve successfully installed the Mattermost server on a bare-metal server ([omnibus](https://docs.mattermost.com/install/installing-mattermost-omnibus.html)), and it’s already installed the Call Plugin.

I opened all the necessary call ports, but after trying to establish a call, it failed.
Here is my JS Console Log:

[Picture](https://global.discourse-cdn.com/business7/uploads/mattermost/original/2X/c/c7c3c27b98b47bdc312caf73b42481d500824b26.jpeg)

I also tried with Chrome and the same thing happend.

**Comment by streamer45** [comment]
@alifiroozi80 Sounds like a possible network misconfiguration assuming you don't have anything on the client blocking UDP traffic. You said you opened the calls ports, the most important one would be UDP 8443. Could you confirm you are able to send and receive data through that?

Something like this should verify that:

1. Temporarily disable the Calls plugin
2. On the instance running the MM server run `nc -l -u 8443`
3. On the client side run `echo "test connectivity" | nc -u CLIENT_FACING_IP 8443`

`CLIENT_FACING_IP` should be the public IP of your MM instance. If everything is correctly setup you should be able to receive the message on the server.

**Comment by alifiroozi80** [comment]
Hello @streamer45, 
Thank you for your quick response, and sorry for my late response.
I did all those steps and received the `test connectivity` message on the MM server.
But still, I can't make any calls.

**Comment by alifiroozi80** [comment]
Hello again, @streamer45,
Strangely, after I disabled and enabled the Plugin, it's working!
Thank you again.
Cheers🍻
