### ISSUE TITLE
Linux Desktop client: cannot see call widget to share desktop

### ISSUE THREAD

**Issue by gitgt** [mattermost/mattermost-plugin-calls#444]
I use Mattermost Desktop app in Linux Mint 21 / Ubuntu 22.04 installed from .deb, v 5.3.1.1 f.
I do not control the server but I see that other users have Jitsi Meet and can share desktop.
When I make a call, I shortly see bottom half of call widget down left, I see it makes another window "Call Widget", but soon after I hover over that half in the main Mattermost windows, even that half disappears.

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/7240617/d7393b97-61c7-4aaa-8eb2-7275f30fb231)

Ttried to search for similar issue, could not find.

**Comment by streamer45** [comment]
Hi @gitgt,

Unfortunately this is a breaking change in the way the widget is rendered on Desktop >= 5.3 which also requires the Calls plugin (or Mattermost) to be up to date (plugin version to at least `v0.13.0`).

My suggestion would be to reach out to the system admin and encourage them to upgrade either the plugin or MM (or both). If that's not possible you can only downgrade your app version to 5.2.x to get it to show correctly.

Similar issues:

https://github.com/mattermost/desktop/issues/2683
https://github.com/mattermost/desktop/issues/2701

**Comment by streamer45** [comment]
Closing this one as the only fix is to upgrade. Please let us know if you need more help with this.
