### ISSUE TITLE
"Start Call" button does not work in Windows application

### ISSUE THREAD

**Issue by ru2mm** [mattermost/mattermost-plugin-calls#47]
In the desktop application for Windows x64, the "Start Call" button is pressed, but call does not start.
In the application for Mac OS, the "Start Call" button is pressed and the call is starting.
When I call from mobile App to Windows App, the call is appier with green button, but I can't enter the call.

Windows App: v5.0.4 or v5.1.0-rc.2 (msi,exe)
Windows 10 (19044.1415)

**Comment by streamer45** [comment]
Hi @ru2mm, would you be able to share full console log output when this happens? I'd expect some kind of error to appear there. 

This is how to show the console:
![console](https://user-images.githubusercontent.com/1832946/165291625-9ea281ee-862f-4efc-b2e9-544402857c76.png)

You can then right click on it and export like so:
![save_console](https://user-images.githubusercontent.com/1832946/165292012-4568210a-d25e-41f3-9e02-c7599cee69de.png)
