### ISSUE TITLE
Calls dont work on IOS , 

### ISSUE THREAD

**Issue by wispoz** [mattermost/mattermost-plugin-calls#477]
Hello i have problem in IOS (calls does not connecting), in Android works fine.
versions: 
 calls: 1.17.0
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/156639/20723d82-60e5-466b-b6c4-0c04648bfcc3)

**Comment by streamer45** [comment]
Have both devices (Android and iOS) been tested from the same network?

**Comment by streamer45** [comment]
@wispoz Did you get this to work?

**Comment by heyValdemar** [comment]
hey @wispoz, please ensure the Mattermost option is enabled in Settings/Privacy & Security/Local Network.

**Comment by bguerin** [comment]
Same as https://github.com/mattermost/mattermost-plugin-calls/issues/451 ?

**Comment by wispoz** [comment]
> Same as #451 ?

I think yes, all ports (8443 udp/tcp) opened and forwarded normally, But on some users works, on some not. I dont fugure out how it works (

**Comment by heyValdemar** [comment]
> Same as #451 ?

Not really, since #451 is about an Android device.

**Comment by heyValdemar** [comment]
> I think yes, all ports (8443 udp/tcp) opened and forwarded normally, But on some users works, on some not. I dont fugure out how it works (

Check out my repos. You might have something wrong with your configuration.

[](https://github.com/heyValdemar?tab=repositories&q=Mattermost&type=&language=&sort=)

**Comment by heyValdemar** [comment]
> I think yes, all ports (8443 udp/tcp) opened and forwarded normally, But on some users works, on some not. I dont fugure out how it works (

Check out my [repos](https://github.com/heyValdemar?tab=repositories&q=Mattermost&type=&language=&sort=). You might have something wrong with your configuration.

**Comment by wispoz** [comment]
> > I think yes, all ports (8443 udp/tcp) opened and forwarded normally, But on some users works, on some not. I dont fugure out how it works (
> 
> Check out my [repos](https://github.com/heyValdemar?tab=repositories&q=Mattermost&type=&language=&sort=). You might have something wrong with your configuration.

thx, but i dont use docker, i installed omnibus

**Comment by bguerin** [comment]
> > Same as #451 ?
> 
> Not really, since #451 is about an Android device.

and I have the exact same message and problem with the desktop app. So I think this is a server problem and not a client one

**Comment by bguerin** [comment]
> > and I have the exact same message and problem with the desktop app. So I think this is a server problem and not a client one
> 
> Can you check if your 8443/UDP port is open? And check if the Call plugin is enabled and set to use this port.

Checked and all ok, see #451

**Comment by bguerin** [comment]
> @bguerin, can you try to run it with my [Docker setup](https://github.com/heyValdemar/mattermost-traefik-letsencrypt-docker-compose)?

I have my own docker compose setup, which is more or less the same as yours

**Comment by heyValdemar** [comment]
I've successfully resolved the issue. The culprit was in the Traefik configuration.

For calls to function correctly, the following lines in the Traefik configuration are essential:

`      - "--entryPoints.calls.address=:8443/udp"`

`      - "8443:8443" `

```
      - "traefik.udp.routers.mm-call-rtr.service=mm-call-svc"
      - "traefik.udp.routers.mm-call-rtr.entrypoints=calls"
      - "traefik.udp.services.mm-call-svc.loadBalancer.server.port=8443"
      - "traefik.http.middlewares.compresstraefik.compress=true"
```

For a comprehensive look, you can view my entire Docker configuration [here](https://github.com/heyValdemar/mattermost-traefik-letsencrypt-docker-compose).

**Comment by streamer45** [comment]
I am going to close this for now. I don't think there's a problem with iOS but more likely a network configuration issue from the mobile side. Please let us know if you need more help with this.
