### ISSUE TITLE
Profile view crash

### ISSUE THREAD

**Issue by wispoz** [mattermost/mattermost-plugin-calls#522]
After update to 0.19 in webapp profile crash (blank screen)

**Comment by danilvalov** [comment]
Error in console:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
```
<img width="423" alt="image" src="https://github.com/mattermost/mattermost-plugin-calls/assets/2463767/22b7e303-4d17-446d-a637-d8ca11a9c1c7">

**Comment by streamer45** [comment]
Thanks all, we are aware of this issue which is getting fixed in https://github.com/mattermost/mattermost-plugin-calls/pull/524 and will be in a v0.19.1 version soon.

**Comment by streamer45** [comment]
This should be now fixed in https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.19.1, closing for now.
