### ISSUE TITLE
Report a JavaScript error after building

### ISSUE THREAD

**Issue by andwang130** [mattermost/mattermost-plugin-calls#527]
go version go1.20.4 
Node.js v16.18.0
npm@8.19.2
 
error
caught TypeError: a is not a function

**Comment by streamer45** [comment]
@andwang130 Could you help sharing the following information?

- Operating system and version
- Command(s) issued to build
- Full logs

**Comment by andwang130** [comment]
have already been solved。Due to operating system issues, successful use of Linux build
