### ISSUE TITLE
Plugin failed to start with MM server 9. Calls: failing to cleanup state if call thread is deleted

### ISSUE THREAD

**Issue by jmvl** [mattermost/mattermost-plugin-calls#535]
https://mattermost.atlassian.net/browse/MM-54520

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/6292978/deba9480-7e82-407f-8232-3887e9cee450)

**Comment by streamer45** [comment]
This issue is getting fixed in Calls v0.19.2

**Comment by streamer45** [comment]
Release is out at https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.19.2, closing this one.
