### ISSUE TITLE
Cannot initiate call from browser or app - call state is missing from channel state

### ISSUE THREAD

**Issue by arminus** [mattermost/mattermost-plugin-calls#548]
## Summary
Cannot initiate call from browser or desktop app,

## Environment Information

Mattermost App Version: 5.5.1
Firefox 118.0.1
Mattermost Server Version: 7.8.12 (self-hosted)
com.mattermost.calls - 0.13.1
Running in docker container, internal call_port 8443 is already in use on the host => mapped to 9443
9443/udp responds when trying to connect from the client machine:
```
nc -uv chat.mydomain.com 9443
Connection to chat.mydomain.com 9443 port [udp/*] succeeded!
```
so my assumption is that there is no firewall or port forwarding issue

## Steps to reproduce
Initiate a call (as admin), either in the desktop app or from Firefox
Connection failed message after a while
Error message in container log (call state is missing from channel state ... main.(*Plugin).handleLeave websocket.go:445)
```
ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 msg=callback failed: call state is missing from channel state ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 msg=callback failed: call state is missing from channel state plugin_id=com.mattermost.calls ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 msg=callback failed: call state is missing from channel state ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > ERR ERR app/plugin_api.go:976 > timestamp=2023-10-10 17:47:20.195 +02:00 msg=callback failed: call state is missing from channel state plugin_id=com.mattermost.calls origin=main.(*Plugin).handleLeave websocket.go:445
```

**Comment by streamer45** [comment]
Hi @arminus,

I notice you are running a quite out of date version of the plugin. As a first step I'd encourage you to upgrade to the latest (v0.20.0) either by manually uploading the [Github release](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.20.0) or using the [marketplace](https://github.com/mattermost/mattermost-plugin-calls/assets/1832946/82472f28-abfb-4273-b660-c4a7bc003fad) (if enabled).

Now, coming to your problem. It sound like there could be a network configuration issue somewhere. You are saying you are running Mattermost in Docker on a non standard port. I'd verify the port is actually forwarded correctly.

Could you share the output of the `docker ps` command?

**Comment by arminus** [comment]
Hi @streamer45 

I just updated to v0.20.0 and here's the output of my docker ps (including keycloak which is "blocking" 8443 on that host and which I can't move to another port:

```
eab12a9b7b94   quay.io/keycloak/keycloak:17.0.1                          "/opt/keycloak/bin/k…"   2 months ago    Up 44 hours             0.0.0.0:8443->8443/tcp, 8080/tcp, 0.0.0.0:9600->9600/tcp                                          keycloak
df4d6e7243e6   mattermost/mattermost-enterprise-edition:7.8              "/entrypoint.sh matt…"   41 hours ago    Up 41 hours (healthy)   8067/tcp, 0.0.0.0:8065->8065/tcp, 8074-8075/tcp, 0.0.0.0:9443->8443/tcp, 0.0.0.0:9443->8443/udp   mattermost-mattermost-1
```
This looks ok to me, and I can successfully connect to 9443 on that host from another host with nc -uv <host's IP> 9443

**Comment by streamer45** [comment]
@arminus Thanks, that shows a potential problem.

`0.0.0.0:9443->8443/tcp, 0.0.0.0:9443->8443/udp` is not going to work as the port number should be the same on both sides. You need to make sure that whatever port you pick is the one you then set in the Calls plugin config:

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/1832946/4562d51b-5621-4c5a-9699-ccd640292b9f)


And then you should forward in docker so that the same port is used on both sides, e.g.:

```
0.0.0.0:9443->9443/tcp, 0.0.0.0:9443->9443/udp
```

I also updated our official docker compose files since they had the same problem when using custom ports (see https://github.com/mattermost/docker/commit/50b14baa2a187e72b3b870c24765657a10d21402).

**Comment by arminus** [comment]
Thanks for you help, highly appreciated!

So, although I don't quite understand why  internal and external port needs to be identical (that's what docker port mapping usually takes care of?), I applied the change as suggested:

The plugin's RTC server ports are now set to 9443, the docker compose file maps like so
```
      - ${APP_PORT}:8065
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp
```
and docker ps now reports 
```
c5ae3dabc80c   mattermost/mattermost-enterprise-edition:7.8              "/entrypoint.sh matt…"   49 minutes ago   Up 49 minutes (healthy)   8067/tcp, 0.0.0.0:8065->8065/tcp, 0.0.0.0:9443->9443/tcp, 8074-8075/tcp, 0.0.0.0:9443->9443/udp   mattermost-mattermost-1
```
(I restarted the container after the changes of course)

Still, no connection and I see this line in the logs:
```
WRN app/plugin_api.go:979 > WRN WRN app/plugin_api.go:979 > timestamp=2023-10-12 20:34:37.350 +02:00 msg=Failed to read from candidate tcp4 host 172.19.0.27:8443: io: read/write on closed pipe plugin_id=com.mattermost.calls WRN 
```
172.19.0.27 is the docker container's network IP, why is it still trying to read from port 8443 there?

Side note: I have ufw port forward rules set up like so
```
[20] 172.19.0.27 9443/tcp       ALLOW FWD   Anywhere                  
[21] 172.19.0.27 9443/udp       ALLOW FWD   Anywhere                  
[22] 9443                       ALLOW IN    Anywhere                  
[28] 9443 (v6)                  ALLOW IN    Anywhere (v6)             
```
These kind of forward rules are basically working since I run keycloak on 8443 on the same host.

**Comment by streamer45** [comment]
@arminus Have you configured the plugin (and restarted) as suggested above to listen on the different port? It should be listening on port 9443 not 8443 as the logs suggest.

**Comment by streamer45** [comment]
>  I don't quite understand why internal and external port needs to be identical

That's because it's an application requirement. The port that gets configured in the plugin is at the same time the one actually used to listen on the network but also the one used to advertise to clients so that they can connect.

**Comment by arminus** [comment]
> @arminus Have you configured the plugin (and restarted) as suggested above to listen on the different port? It should be listening on port 9443 not 8443 as the logs suggest.

Yes, I had restarted but for some strange reason, it still listened on 8443 (actually built a custom image with net-tools installed to confirm that). But I have it working now, switched to the latest mattermost image (from 7.8 as was set in the .env I had originally downloaded), manually wiped all traces of com.mattermost.calls (which lived both in mattermost/plugins **and** mattermost/client/plugins ...), reinstalled the plugin, set it to 9443 and the client is finally able to connect :-)

My only gripe would be that it could be stated somewhere prominently, that the internal and external ports really need to be identical. This is not what I would have expected, because the typical way with any/most other services running inside a docker container, is to simple re-map the internal port to another external port if the default internal port is already taken on the host.

I think I understand the reason in this case, but I don't think this is obvious right away.

Anyway, thanks a lot for your help!

**Comment by streamer45** [comment]
@arminus, glad you got it working. I agree it's an important detail but I suppose we didn't expect people to change the port number that often so it was a case left undocumented. I'll make sure to improve that, thank you for the great feedback :)

Closing this for now.
