### ISSUE TITLE
Issues with Calls Plugin - "Invalid 1:1 NAT IP Mapping" Error

### ISSUE THREAD

**Issue by iain-neirfeno** [mattermost/mattermost-plugin-calls#552]
I have recently installed the Mattermost self-hosted server and am trying to set up the Calls plugin. However, I am facing issues with users being unable to connect to calls. The users get stuck at "connecting to the call..." and I see an "invalid 1:1 NAT IP mapping" error in the server logs.

**Steps to Reproduce:**
1. Installed Mattermost self-hosted server.
2. Opened port 8443 for both TCP and UDP on the server.
3. Attempted to make a call using the plugin.

**Expected Behavior:**
The call should connect and users should be able to communicate with each other.

**Observed Behavior:**
Users get stuck at "connecting to the call..." and an "invalid 1:1 NAT IP mapping" error is observed in the server logs.

**Troubleshooting Steps Taken:**
1. Verified that UDP messages can be sent from the client to the server on port 8443.
2. Confirmed that the plugin is listening on port 8443.
3. Checked plugin and Mattermost server configurations.
4. Set the RTC server and ICE Host Override to the external IP address of the server.
5. Removed ICE Servers Configurations.

**Mattermost Server Version:**
9.1.0

**Calls Plugin Version:**
0.20.0

**Comment by streamer45** [comment]
@iain-neirfeno Hi, the error you mentioned suggest there may be a problem with the ICE Host Override setting. Are you able to share your current config?

**Comment by streamer45** [comment]
Also, if you enable DEBUG level logging, you should see a log line starting with `generated remote/local addrs pairs`. May be useful to see the full content of that.

**Comment by streamer45** [comment]
@iain-neirfeno Thanks. There seems to be some duplication with the public IP likely causing issues.

Is that an address actually mapped to a local interface? Could you share the output of the `ip a` command perhaps?

Usually the plugin would be listening on a private interface/IP and then we'd use the `ICE Host Override` to create a map from external (public) to internal (private). 

As a first thing I'd probably try to blank both `RTC Server Address (UDP)` and `RTC Server Address (TCP)` settings and restart the plugin.

**Comment by iain-neirfeno** [comment]
Hi @streamer45, Yes, the public interface of the server is directly mapped to the internet. There's no NAT in front of the server. Again, with the actual IP address substituted, here's the output of `ip a`:
```
~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 1a:2b:3c:4d:5e:6f brd ff:ff:ff:ff:ff:ff
    inet 12.34.56.78 peer 12.34.56.1/32 brd 12.34.56.78 scope global enp0s31f6
       valid_lft forever preferred_lft forever
    inet 12.34.56.78/32 scope global enp0s31f6
       valid_lft forever preferred_lft forever
    inet6 0012:034:56:078::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 aa12::aa34:aa56:aa78:090/64 scope link 
       valid_lft forever preferred_lft forever
```

I also tried removing the configuration for both `RTC Server Address (UDP)` and `RTC Server Address (TCP)`, making them blank as suggested, and the output in the logs is identical (the duplicate IP mapping is still present).

Thank you for your help with this, I'm confident we will get it sorted soon.

**Comment by streamer45** [comment]
@iain-neirfeno Understood. Can you try setting the `ICE Host Override` to `12.34.56.78/12.34.56.78` and try once more (after restarting)?

**Comment by iain-neirfeno** [comment]
This is it. Thank you so much for your help with this.
