### ISSUE TITLE
MacOS app - In call the same user appears both muted and unmuted

### ISSUE THREAD

**Issue by andreineacsu** [mattermost/mattermost-plugin-calls#572]
#### Summary
MacOS app - In call the same user appears both muted and unmuted

### Environment Information
  - Device Name: MacOS
  - OS Version: 14.1.1 (23B81)
  - Mattermost App Version: Version 5.5.1 (63830002741)
  - Mattermost Server Version: 9.2.2

#### Steps to reproduce
1. Start a group call
2. Make sure you are not muted
3. Start a screen share
4. Pop out the screen
5. in the pop out screen the user appears to be muted

![Uploading Screenshot 2023-11-23 at 14.37.36.png…]()

#### Expected behavior
The muted status should be consistent across screens.

**Comment by streamer45** [comment]
@andreineacsu Thanks for the report. Could you confirm your Mattermost Calls version?

**Comment by andreineacsu** [comment]
It's 0.20.0

**Comment by streamer45** [comment]
@andreineacsu A couple of questions:

- Is this easily reproducible or does it happen sporadically?
- I see you mention screen sharing in your steps but from the screenshot I don't see any screen share. Is screen sharing needed to trigger the issue?

In the meantime I'd try to upgrade the plugin to the latest version v0.21.1 and see if anything improves.

**Comment by andreineacsu** [comment]
@streamer45 Can you provide me with some steps/documentation on how to update the plugin?

**Comment by streamer45** [comment]
You can do it either by manually uploading the [Github release](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.21.1) from the *Plugin Management* system console section or using the [marketplace](https://github.com/mattermost/mattermost-plugin-calls/assets/1832946/82472f28-abfb-4273-b660-c4a7bc003fad) (if enabled).

**Comment by andreineacsu** [comment]
Thank you. I will test more tomorrow.

**Comment by andreineacsu** [comment]
I have tested this and I can't reproduce it on v0.21.1.
