### ISSUE TITLE
Large Window no longer working with Mattermost 9.2.3

### ISSUE THREAD

**Issue by pampersrocker** [mattermost/mattermost-plugin-calls#578]
After Upgrading the Mattermost Version from 8.0.1 to 9.2.3 and having Plugin 0.21.1 installed, the Large Windows for Screen Sharing etc is no longer working and opens a broken window with a message "An error occurred in the com.mattermost.calls plugin":
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/1851043/a72345b3-1cb4-4a71-9c8b-2b1dd3702e36)

The refresh button does nothing.
There are no notable error messages on the server and clients logs as far as I can tell.

Starting a Screen Share works, but no one can watch it as the pop-out no longer works.

Using Desktop Client 5.5.1

**Comment by streamer45** [comment]
@pampersrocker Could you open the developers tool on the popout window and share any errors from the console? You should be able to use one of the following shortcuts depending on your system:

Linux/Windows: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>
MacOS: <kbd>Cmd</kbd>+<kbd>Option</kbd>+<kbd>I</kbd>

Also, can you confirm if the error happens on Desktop only or also when opening the window from a web browser?

**Comment by pampersrocker** [comment]
Without any restart of the server or any other changes, it now started to work 24 hours later. Not sure if any cached stuff timed out or whatever, but it is now resolved on multiple clients.

Sorry for the inconvenience.
