### ISSUE TITLE
Bug: JS console error on clicking user tile after call

### ISSUE THREAD

**Issue by Akshaychdev** [mattermost/mattermost-plugin-calls#605]
![mm_err_2](https://github.com/mattermost/mattermost/assets/63786863/e0b3430e-6c8d-4f94-8a9b-a1eb45375ac7)

#### Summary
On clicking the User icon tile(avatar) after completing a Call, a JS error shown on console
It will not show after a reload.

Installation info

Mattermost Version: 8.1.7
Database Schema Version: 113
Build Number: 7025434773
Database: mysql

#### Steps to reproduce
1. Make a call.
2. Hit the leave call.
3. Click the Avatar icon. 
4. The error will be reported on every avatar click until a reload.

#### Expected behavior
It need to behave as usual by just displaying the user popup details.

#### Observed behavior (that appears unintentional) 
Shows the mentioned error in the screenshot, a red notification on top.

#### Possible fixes
Null

**Comment by streamer45** [comment]
I believe we fixed this. @Akshaychdev could you confirm your Calls plugin version?

**Comment by streamer45** [comment]
Closing this as it should be fixed in the latest version. Please feel free to comment further if it needs revisiting.
