### ISSUE TITLE
Group calls not possible: json: cannot unmarshal number into Go struct field callStats.call.stats.participants of type map[string]struct {}

### ISSUE THREAD

**Issue by r0l1** [mattermost/mattermost-plugin-calls#626]
The calls plugin does not work for groups. I get the following warning log message:

```
failed to lock call: failed to get channel state: json: cannot unmarshal number into Go struct field callStats.call.stats.participants of type map[string]struct {}
```

Calls Plugin: 0.23.1
Mattermost Version: 9.4.1 (Docker)
Database Schema Version: 117
Build Number: 7424719315
Database: postgres

**Comment by streamer45** [comment]
@r0l1 Sounds like you may have stale calls data in your database. I'd suggest to identify the channel id where this is happening and run the following SQL query to clear it:

```sql
DELETE FROM PluginKeyValueStore WHERE PluginId = 'com.mattermost.calls' AND PKey = 'CHANNEL_ID';
```

**Comment by r0l1** [comment]
@streamer45 thanks a lot for your hint! That worked and solved the problem.
How did this happen? Are any fixes required for the plugin? Otherwise I will close this issue.

**Comment by streamer45** [comment]
I assume this happened either due to DB faults or a sudden application crash. The plugin should normally try to cleanup its old state on startup. The error was due to a change we made in a recent version so it won't happen again once manually fixed unless you have more old calls stuck in there.
