### ISSUE TITLE
Popout Calls window not possible since last Mattermost update // "Leave and join new call" problem

### ISSUE THREAD

**Issue by rtfm98** [mattermost/mattermost-plugin-calls#629]
Hey there,

we have the following environment:

Mattermost: 8.1.8 (ESR)
Mattermost Calls: 0.23.1 (v8.1.8 is packaged with 0.21.1, but we updated the Calls plugin manually after these problems occured, because we wanted to ensure that they aren't fixed yet in a later version)
Mattermost desktop client: 5.6.0 (on Windows)

1. problem:

Since the last Mattermost update from 8.1.7 to 8.1.8 we have the following problem: when we try to popout the Calls window in a group call, the following message appears:

![mattermost_calls_problem](https://github.com/mattermost/mattermost-plugin-calls/assets/15339915/f4687cbd-c184-4026-a8f4-eca5d5096201)

In a direct call with one person, popping the window out is working.
Clicking on "Refresh" didn't help.
The Console log only says "Starting Mattermost v5.6.0 commit: aebafea", that's the last entry.
The Mattermost log itself says:

```
{
  "caller": "app/plugin_api.go:976",
  "level": "error",
  "msg": "Incoming unhandled RTP ssrc(4285125416), OnTrack will not be fired. mid RTP Extensions required for Simulcast",
  "origin": "webrtc/v3.(*PeerConnection).undeclaredRTPMediaProcessor.func1 github.com/pion/webrtc/v3@v3.2.21/peerconnection.go:1673",
  "plugin_id": "com.mattermost.calls",
  "timestamp": "2024-01-23 10:03:07.991 +01:00"
}
```

2. problem:

This also happens since the last update. "Leave and join new call" pops out, although we already left the other call. This happens after being in a group call and calling in a direct channel afterwards. The other way round (first: direct call, second: group call) this problem doesn't seem to happen.

Are both problems reproducible or already known? If you need more information please let me know and I'd be happy to help!

Best regards
Ben

**Comment by streamer45** [comment]
@rtfm98 I'd expect some errors to appear in the client JS logs console. Could you share those? From the desktop app you can access them through `Three dots menu -> View -> Developer Tools for Current Server`

**Comment by rtfm98** [comment]
@streamer45 Thanks for your fast reply! In the meantime, for some reason, both problems no longer occur. Maybe this was some cache-related stuff.. Sorry for the disturbance and thanks for the tip with the Developer Tools!

We have another problem, though, that is reproducible on our test environment as well. But I'm going to create another issue for this as this isn't related to the above mentioned problems.
