### ISSUE TITLE
User profiles not openable while being in a call

### ISSUE THREAD

**Issue by rtfm98** [mattermost/mattermost-plugin-calls#630]
Hey there,

we have the following environment:

Mattermost: 8.1.8 (ESR)
Mattermost Calls: 0.23.1 (v8.1.8 is packaged with 0.21.1, but we updated the Calls plugin manually after these problems occured, because we wanted to ensure that they aren't fixed yet in a later version)
Mattermost Calls in our test environment: 0.21.1
Mattermost desktop client: 5.6.0 (on Windows)

We believe that this problem occurs since the last Mattermost update from 8.1.7 to 8.1.8.

While being on a call and clicking on a user profile, the following error message appears at the top bar (in the desktop client as well as the browser):
> A JavaScript error has occurred. Please use the JavaScript console to capture and report the error

In the JS Console, I see the following:

```
TypeError: i is not iterable
    at index.ts:60:28
    at Array.forEach (<anonymous>)
    at Re (index.ts:57:24)
    at Ne.actions.closeModal [as mapToProps] (index.ts:120:42)
    at n (wrapMapToProps.js:41:46)
    at n.mapToProps (wrapMapToProps.js:55:17)
    at n (wrapMapToProps.js:41:46)
    at selectorFactory.js:22:18
    at connectAdvanced.js:319:16
    at Object.useMemo (react-dom.production.min.js:172:115)
iu	@	react-dom.production.min.js:216
t.callback	@	react-dom.production.min.js:216
pa	@	react-dom.production.min.js:131
mu	@	react-dom.production.min.js:220
Li	@	react-dom.production.min.js:259
n.unstable_runWithPriority	@	scheduler.production.min.js:18
Hl	@	react-dom.production.min.js:122
zi	@	react-dom.production.min.js:252
vi	@	react-dom.production.min.js:243
(anonymous)	@	react-dom.production.min.js:123
n.unstable_runWithPriority	@	scheduler.production.min.js:18
Hl	@	react-dom.production.min.js:122
Kl	@	react-dom.production.min.js:123
ql	@	react-dom.production.min.js:122
Me	@	react-dom.production.min.js:292
Xn	@	react-dom.production.min.js:73

index.js:3404 [Util] handleError::  Uncaught TypeError: i is not iterable

focalboard_bc5a129749169408_bundle.js:2 [Util] handleError::  Uncaught TypeError: i is not iterable

react-dom.production.min.js:123 Uncaught TypeError: i is not iterable
    at index.ts:60:28
    at Array.forEach (<anonymous>)
    at Re (index.ts:57:24)
    at Ne.actions.closeModal [as mapToProps] (index.ts:120:42)
    at n (wrapMapToProps.js:41:46)
    at n.mapToProps (wrapMapToProps.js:55:17)
    at n (wrapMapToProps.js:41:46)
    at selectorFactory.js:22:18
    at connectAdvanced.js:319:16
    at Object.useMemo (react-dom.production.min.js:172:115)
(anonymous)	@	index.ts:60
Re	@	index.ts:57
Ne.actions.closeModal	@	index.ts:120
n	@	wrapMapToProps.js:41
n.mapToProps	@	wrapMapToProps.js:55
n	@	wrapMapToProps.js:41
(anonymous)	@	selectorFactory.js:22
(anonymous)	@	connectAdvanced.js:319
useMemo	@	react-dom.production.min.js:172
t.useMemo	@	react.production.min.js:23
O	@	connectAdvanced.js:304
ao	@	react-dom.production.min.js:157
Wo	@	react-dom.production.min.js:180
Vo	@	react-dom.production.min.js:178
Ao	@	react-dom.production.min.js:177
$u	@	react-dom.production.min.js:274
Ni	@	react-dom.production.min.js:250
_i	@	react-dom.production.min.js:250
Ci	@	react-dom.production.min.js:250
vi	@	react-dom.production.min.js:243
(anonymous)	@	react-dom.production.min.js:123
n.unstable_runWithPriority	@	scheduler.production.min.js:18
Hl	@	react-dom.production.min.js:122
Kl	@	react-dom.production.min.js:123
ql	@	react-dom.production.min.js:122
Me	@	react-dom.production.min.js:292
Xn	@	react-dom.production.min.js:73
```

After the call, the problem still occurs. After a normal refresh (Strg+R, instead of Strg+Shift+R), everything works fine as before and the user profiles are openable as well.

Is this a known bug? Is this reproducible at your side?

Best regards!

**Comment by streamer45** [comment]
@rtfm98 This is a known issue which we fixed a while back. I am surprised it's happening on the latest version unless there's a regression. Can you reproduce from a web browser as well? I can't seem to reproduce on v9.

**Comment by streamer45** [comment]
Was able to reproduce this in MM v8 with the newer Calls versions. It's a compatibility change that happened in the plugin and broke something on older MM versions (< v9) I think. We'll look into this.

**Comment by streamer45** [comment]
Created https://mattermost.atlassian.net/browse/MM-56659 for internal tracking. /cc @cpoile

**Comment by rtfm98** [comment]
@streamer45 Thanks for your fast reply! To answer your question:

> Can you reproduce from a web browser as well?

Yes, we can reproduce this on Google Chrome as well.

Thanks for testing this on MM v8 and for reproducing the problem.

**Comment by streamer45** [comment]
Fix here is to upgrade Mattermost to the latest ESR (v9.5). Closing for now.
