### ISSUE TITLE
Cannot verify released package

### ISSUE THREAD

**Issue by netrix** [mattermost/mattermost-plugin-calls#638]
I wanted to manually update plugin on my  instance so I decided to download a released package along with .sig file from Release assets.

I run following command and received this output:
```
% gpg2 --verify com.mattermost.calls-0.24.0.tar.gz.sig com.mattermost.calls-0.24.0.tar.gz
gpg: Signature made Fri 09 Feb 2024 11:44:19 PM CET
gpg:                using RSA key C55881B80F69E863B85AD5D1D1B54B47A5CEFEC4
gpg: Can't check signature: No public key
```
I am looking around the interned to find a keyserver that will allow me to get this public key but it's not available anywhere. How am I suppose to verify if this package is really what it suppose to be ?

**Comment by streamer45** [comment]
Hi @netrix, here's the public key used to sign our plugin builds:

[plugin-build-public-key.txt](https://github.com/mattermost/mattermost-plugin-calls/files/14334764/plugin-build-public-key.txt)

I'll make sure to update our documentation so that it can be easily recovered and imported next time.

**Comment by netrix** [comment]
Thank you, it works.

```
% gpg2 --verify com.mattermost.calls-0.24.0.tar.gz.sig com.mattermost.calls-0.24.0.tar.gz           
gpg: Signature made Fri 09 Feb 2024 11:44:19 PM CET
gpg:                using RSA key C55881B80F69E863B85AD5D1D1B54B47A5CEFEC4
gpg: Good signature from "Mattermost, Inc. <support@mattermost.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C558 81B8 0F69 E863 B85A  D5D1 D1B5 4B47 A5CE FEC4
```
