### ISSUE TITLE
The plugin does not apply the language set by the user

### ISSUE THREAD

**Issue by wensimin** [mattermost/mattermost-plugin-calls#651]
mattermost version : mattermost-team-edition:release-9.6
com.mattermost.calls version:  0.24.0
I see the following error message in the console

![1709630440460](https://github.com/mattermost/mattermost-plugin-calls/assets/11828594/fe7e6777-01a1-42b0-818b-b94e23d0ef2b)

Did I get something wrong?

**Comment by streamer45** [comment]
Hi @wensimin, it looks like we don't have translations for that specific language code. I am wondering if this is a simple issue of language identifiers. Would any of the following translation files apply to you?

https://github.com/mattermost/mattermost-plugin-calls/blob/main/webapp/i18n/zh_Hans.json

https://github.com/mattermost/mattermost-plugin-calls/blob/main/webapp/i18n/zh_Hant.json

**Comment by wensimin** [comment]
Yes, I think it is zh_Hans.json @streamer45 

But I can't find this in the packaged file

Is there a way for me to change this code manually?

Thank you

**Comment by wensimin** [comment]
Thanks for your work！

Claudio Costa ***@***.***> 于 2024年3月6日周三 上午10:29写道：
