### ISSUE TITLE
Setting site url is not used in mattermost desktop

### ISSUE THREAD

**Issue by wensimin** [mattermost/mattermost-plugin-calls#660]
I have a mattermost service at https://mydomain/mattermost/
But calls requested the following API in Windows Desktop
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/11828594/5af47fe6-8cab-4aa0-99ec-4323afc87dcf)
The correct request should be
`:3000/mattermost/api/v4/channels/c8h6b3jy4ibni86jjzry53r1uc`
not `:3000/api/v4/channels/c8h6b3jy4ibni86jjzry53r1uc`
My setting
![image](https://github.com/mattermost/mattermost-plugin-calls/assets/11828594/e162e5ab-08e4-4602-aa9a-f34e0dbd0720)

**Comment by streamer45** [comment]
Thanks for the report @wensimin. We should definitely fix this asap, I filed am internal ticket at https://mattermost.atlassian.net/browse/MM-57327
