### ISSUE TITLE
Update 9.4< and after are breaking calls

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost-plugin-calls#664]
Summary
After upgrading the Mattermost server, the calls stopped working.
And the calls api gives error 500

Log:
{
  "caller": "plugin/client_rpc_generated.go:654",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call OnWebSocketDisconnect to plugin failed.",
  "plugin_id": "com.mattermost.calls",
  "timestamp": "2024-03-19 13:22:25.489 +05:00"
}
{
  "caller": "plugin/client_rpc_generated.go:689",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call WebSocketMessageHasBeenPosted to plugin failed.",
  "plugin_id": "com.mattermost.calls",
  "timestamp": "2024-03-19 13:22:25.489 +05:00"
}
{
  "caller": "plugin/client_rpc_generated.go:33",
  "error": "connection is shut down",
  "level": "error",
  "msg": "RPC call OnDeactivate to plugin failed.",
  "plugin_id": "com.mattermost.calls",
  "timestamp": "2024-03-19 13:22:26.543 +05:00"
}

<img width="1409" alt="Снимок экрана 2024-03-19 в 13 28 36" src="https://github.com/mattermost/mattermost-plugin-calls/assets/109951790/e533bf15-e1df-4443-953e-e6237b0fd8db">

Edition:Mattermost 9.6.1
Version: com.mattermost.calls - 0.25.0

**Comment by streamer45** [comment]
@KakEgorka We'll need more server logs to help as none of those is explaining why the plugin failed. Also it would be good to see your config.

You can everything privately by sending me a DM on our [Community server](https://community.mattermost.com/). You can reach me as `@claudio.costa`.

**Comment by KakEgorka** [comment]
> @KakEgorka We'll need more server logs to help as none of those is explaining why the plugin failed. Also it would be good to see your config.
> 
> You can share everything privately by sending me a DM on our [Community server](https://community.mattermost.com/). You can reach me as `@claudio.costa`.

Hi
I would like to clarify that this problem is not specific to one plugin. The same issue is observed with other plugins: playbooks, focalboard, Jitsi 
There appears to be a significant issue with the plugin API. When reverting to version 9.2 of the server, the problem disappears. The plugin versions remain the same.

**Comment by streamer45** [comment]
Confirmed this was an issue with Golang v1.22 (https://github.com/golang/go/issues/65633) which we don't yet use to build neither plugins nor MM server. For custom builds please use v1.21 until a fix is released.
