### ISSUE TITLE
Calls not enabled

### ISSUE THREAD

**Issue by spbdimka** [mattermost/mattermost-plugin-calls#680]
### Environment Information
  - Device Name: ios/android
  - OS Version: avtual
  - Mattermost App Version: 1.24.0
  - Mattermost Server Version: 9.6.0

#### Steps to reproduce
Try to init voip call

#### Expected behavior
voip call. while official app from appstore can make calls connected to my self-hosted server, calls plugin enabled and i can call via browser

#### Observed behavior (that appears unintentional)
Error "Calls not enabled"

Maybe i missed any parameter due building apps or calls plugin answers incorrect (can i test it by curl some context?)

**Comment by streamer45** [comment]
@spbdimka Sounds like Test mode may be still on. Could you check the config?

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/1832946/5b61ca60-bab8-4d8f-b44a-cd6f7ec10431)

**Comment by spbdimka** [comment]
Yep, its disabled, both in web and in cli, also tried initiate call by admin

**Comment by streamer45** [comment]
Can you share a screenshot of the error?

**Comment by spbdimka** [comment]
![IMG_0497](https://github.com/mattermost/mattermost-plugin-calls/assets/11237571/6b708365-49bf-44da-96ce-db0494c3d9f7)
Calls is not enabled, contact administrator

**Comment by streamer45** [comment]
@cpoile Do you remember what would cause this to appear on mobile?

**Comment by cpoile** [comment]
So the official build works, but the custom build doesn't?

If that's the case, I'm not exactly sure what the difference would be.

@spbdimka  Could you type out the error message for me? Then I can find out which one it is in the code, and then I can better understand where it's happening.

**Comment by spbdimka** [comment]
mobile.calls_not_available_title in i18n

**Comment by streamer45** [comment]
@spbdimka Looks like it's simply trying to fetch the `/version` endpoint.

```
curl http://SITE_URL/plugins/com.mattermost.calls/version
```

**Comment by spbdimka** [comment]
and its normaly answers {"build":"82f0939e8078bb0bf72b3f0b2268316045e1c330","version":"0.24.0"}

**Comment by spbdimka** [comment]
also go to /config
It’s confusing that ICEServers is always null, regardless of whether I fill it in or not in the settings
 
```
   "ICEServers": null,
   "ICEServersConfigs": [
     {
       "urls": [
         "stun:stun.global.calls.mattermost.com:3478"
       ]
     }
   ],
   "AllowEnableCalls": true,
   "DefaultEnabled": true,

```  
  
  
   I also collected a log from the device, I see the line 
`2024/04/06 17:31:59:310 DEBUG error on fetchBindings Received invalid response from the server.; JSON could not be serialized because of error:`
   I have no idea where it’s knocking and who is giving the curved json, but it seems to come out when I try to initiate a call

**Comment by streamer45** [comment]
@spbdimka `ICEServers` is a deprecated setting so it's not used anymore, hence why it's `null`. The new setting is `ICEServersConfigs` which needs to be a valid JSON array. Can you share the full error logs?

**Comment by spbdimka** [comment]
yes, I found a problem in my build
globally changed the bundle ID and changed the name of the plugin, so it turned to .../my.bundleid.calls/version
thanks for the quick replies, I'm a fool to myself

**Comment by streamer45** [comment]
Yeah, the ID is used in a lot of places so it's better if left unchanged.
