### ISSUE TITLE
Please don't retag releases after they go out

### ISSUE THREAD

**Issue by alerque** [mattermost/mattermost-plugin-calls#687]
I packaged this plugin for Arch Linux when it was first released, but now the package cannot be reproduced because the source tag has been deleted and retagged on a new commit. Now the checksums are a missmatch. Just bump the patch number and release again if something went wrong with the release process. Given most distros work on a trust-on-first-use model, this creates a lot of work for downstream folks to figure out what changed, verify the change is not malicious, and get things re-released.

**Comment by streamer45** [comment]
Apologies, it was an honest mistake on our side. We'll try to be more careful.
