### ISSUE TITLE
v0.26.1 assets version mismatch

### ISSUE THREAD

**Issue by alerque** [mattermost/mattermost-plugin-calls#688]
As a follow up to #687, the assets that got attached to the new [v0.26.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.26.1) tag (:+1: for that) are still labeled as '-0.26.0'. I didn't check inside the assets, but presumably there is going to be an internal version mismatch to. I'm guessing these just got re-uploaded from a previous build rather than going through the normal build/release cycle.

**Comment by streamer45** [comment]
Indeed, there was some malfunctioning with the automated pipeline. We are planning a `v0.26.2` release sometime today.

**Comment by streamer45** [comment]
Should be good this time around, thanks for reaching out :)
