### ISSUE TITLE
Allow screen sharing - can not be activated

### ISSUE THREAD

**Issue by benschhold** [mattermost/mattermost-plugin-calls#720]
In mattermost calls section the allow screen sharing option is listed as activated but if you look in the config its set to false and the feature cant be used. The only way to get the feautre working again is by disabling the plugin, change the config manually to true and start the plugin. If you then turn the calls plugin off and on again in the webinterface, you have the bug again.

Logs when you try to save the config:

{"timestamp":"2024-05-02 11:30:32.626 Z","level":"warn","msg":"Unrecognized config permissions tag value.","caller":"api4/config.go:431","path":"/api/v4/config/patch","request_id":"w1zkkj6nzbnd7g7gbkdy7dspch","ip_addr":"10.233.75.18","user_id":"hhoqr49ww7y4zxbfab4i93fkpo","method":"PUT","tag_value":"sysconsole_write_*_read"}
{"timestamp":"2024-05-02 11:30:32.636 Z","level":"debug","msg":"ConfigurationWillBeSaved","caller":"app/plugin_api.go:997","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).ConfigurationWillBeSaved configuration.go:477"}

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/6053068/fbcd2755-ef43-412e-a1af-9c5375862ddb)

![image](https://github.com/mattermost/mattermost-plugin-calls/assets/6053068/a1632034-2671-43f2-bcd8-3502d61b45f7)

**Comment by streamer45** [comment]
Thanks for the report @benschhold , I can indeed reproduce it. It's very likely a regression on Mattermost, we'll have a look.

@cpoile This sounds too similar to https://mattermost.atlassian.net/browse/MM-57570 for being a coincidence, would you be able to confirm?

**Comment by cpoile** [comment]
@streamer45 Yes, can confirm. Looks similar to the previous issue. It looks like it happens to any bool that has a default of `true`. I will make a ticket.

**Comment by streamer45** [comment]
Thank you!
