### ISSUE TITLE
Unable to connect to the voice call: timed out waiting for peer connection

### ISSUE THREAD

**Issue by Kuuchuu** [mattermost/mattermost-plugin-calls#729]
Calls plugin does not work, connection times out. Tested Mobile to Mobile & Desktop to Mobile (and vice versa)

## Environment
**Mattermost Server**: Docker 9.7.3, Teams Edition
**Mattermost Android App**: 2.15.0
**Calls Plugin**: 0.26.2
**Host**: Hetzner Cloud VPS, NixOS 23.11, Docker Engine 24.0.5
**Firewall**: Port 8443 opened on Hetzner Cloud Firewall, NixOS firewall disabled

## Additional Details
Coturn server configured and working.

Coturn turn & stun URLs inputted into "ICE Servers Configurations".

Port 8443 has been opened in the firewall, "yougetsignal" Port Forward Tester tool reports port opened.

Mattermost Docker container has port 8443 udp & tcp directly assigned to it. (Mattermost Docker container port 8065 routed through NGINX)

"RTC Server Address" set to 0.0.0.0, tested leaving field empty as well with no change.

"Server Side TURN" set to On.

Running `nc -l -u 0.0.0.0 8443` inside the docker container (as root, after install netcat inside the container) seems to time out. Same with `nc -u -v chat.*****.** 8443` on my client computer where Mattermost desktop runs.

----------

Any help troubleshooting this issue would be really appreciated!

**Comment by streamer45** [comment]
@Kuuchuu Sounds like a clear networking issue. You should be able to run the netcat checks and see data coming in/going out.

It may be quicker to debug this if you DM me on our [Community server](https://community.mattermost.com/). You can find me as `@claudio.costa`.

**Comment by streamer45** [comment]
I'm closing this for now as it's related to network configuration. Please reach out again if you still need help with this.
