### ISSUE TITLE
Error updating to 0.28.1 from marketplace

### ISSUE THREAD

**Issue by chahn** [mattermost/mattermost-plugin-calls#788]
Attempting to update to 0.28.1 in App Marketplace, I'm getting the following error: plugin signature cannot be verified:

<img width="745" alt="Screenshot 2024-06-18 at 20 55 29" src="https://github.com/mattermost/mattermost-plugin-calls/assets/3457827/b732e0b5-dcf7-44ed-a868-6885c127aca6">

I am using Mattermost-Version: 9.9.0

The Mattermost system console log:
 
`error [2024-06-18 20:55:13.417 +02:00] Unable to verify plugin signature. caller="web/context.go:115" path=/api/v4/plugins/marketplace request_id=xxxxxxxxxxxxx ip_addr="xxxxxxxxxxxxxx" user_id=xxxxxxxxxxxxxxx method=POST err_where=VerifyPlugin http_code=500 error="VerifyPlugin: Unable to verify plugin signature."`

Thanks a lot
Christian

**Comment by Alwaysin** [comment]
Same on Mattermost version 9.7.2

**Comment by streamer45** [comment]
@phoinixgrr This sounds like a problem with the new release builds.

**Comment by streamer45** [comment]
@chahn, @Alwaysin Thank you for the report. We are looking into this (https://mattermost.atlassian.net/browse/MM-58833).

**Comment by chahn** [comment]
@streamer45 @phoinixgrr Thank you very much for taking care of this!

**Comment by streamer45** [comment]
We identified the issue. Will be sending a fix today.

**Comment by streamer45** [comment]
This should be fixed; please give it a try and let us know.

**Comment by chahn** [comment]
LGTM! The update was successful.
Thanks a lot!
