### ISSUE TITLE
message was dropped by rate limiter

### ISSUE THREAD

**Issue by perkooo** [mattermost/mattermost-plugin-calls#86]
Hello,

I'm getting this message below in logs when I'm trying to open a call (in particular when I unmute my microphone):

`
May 27 06:49:21 mattermost mattermost[18506]: {"timestamp":"2022-05-27 06:49:21.772 Z","level":"error","msg":"message was dropped by rate limiter","caller":"app/plugin_api.go:940","plugin_id":"com.mattermost.calls","origin":"main.(*Plugin).WebSocketMessageHasBeenPosted websocket.go:547","msgType":"ice","userID":"x8cg86aefpfjjpqs4mjqjoo51y","connID":"o7cppry7jj8u7n5dit4hxd9wqe"}`

I checked in mattermost configuration the parameter **RateLimitSettings** (in case it was related) but no impact on it, also set as **False**.
Same issue if I use mattermost STUN default or mine.

My version is 0.5.3 (same with 0.5.1), first time I'm testing this plugin.

Any idea?

**Comment by streamer45** [comment]
Hi, 

the plugin uses its own rate limiter which has currently a constant rate value of 2 events per second + 30 events of burst for things like ice candidates which is typically what triggers it like in your case. 

I'll create a ticket to tune it a bit higher to account for this and maybe consider making it configurable.

**Comment by perkooo** [comment]
Sure thanks, it happens even if I'm alone or only with two people (so it never works).

**Comment by perkooo** [comment]
Thanks for the update.

I noticed that the issue was due to my Mozilla Firefox plugin "uBlock Origin".
After disabling it, the rate limiter message just stopped.
